// Comprehensive word banks for all word-based games
// Organized by difficulty level with 100+ words each for endless variety

export interface WordWithHint {
  word: string
  hint: string
}

export interface WordPair {
  word: string
  definition: string
}

// ==================== WORD MATCH WORD BANK ====================

export const WORD_MATCH_EASY: WordPair[] = [
  { word: 'Apple', definition: 'A common fruit that keeps the doctor away' },
  { word: 'Book', definition: 'Contains pages with text or images for reading' },
  { word: 'Sun', definition: 'The star that provides light and warmth to Earth' },
  { word: 'Water', definition: 'Essential clear liquid needed for all life' },
  { word: 'Tree', definition: 'A tall plant with branches, leaves, and trunk' },
  { word: 'Car', definition: 'A vehicle with four wheels used for transport' },
  { word: 'House', definition: 'A building where people live' },
  { word: 'Friend', definition: 'Someone you trust and enjoy spending time with' },
  { word: 'Dog', definition: 'A loyal pet that barks and wags its tail' },
  { word: 'Cat', definition: 'A small pet that meows and purrs' },
  { word: 'Fish', definition: 'An animal that lives in water and has gills' },
  { word: 'Bird', definition: 'An animal with feathers that can fly' },
  { word: 'Moon', definition: 'The natural satellite visible in the night sky' },
  { word: 'Star', definition: 'A bright point of light in the night sky' },
  { word: 'Rain', definition: 'Water falling from clouds in drops' },
  { word: 'Snow', definition: 'Frozen water crystals falling from the sky' },
  { word: 'Wind', definition: 'Moving air that you can feel but not see' },
  { word: 'Fire', definition: 'Hot flames produced by burning material' },
  { word: 'Rock', definition: 'A hard solid piece of mineral material' },
  { word: 'Sand', definition: 'Tiny particles found on beaches and deserts' },
  { word: 'Milk', definition: 'White liquid produced by cows and goats' },
  { word: 'Bread', definition: 'Food made from flour, water, and yeast' },
  { word: 'Egg', definition: 'An oval food laid by chickens' },
  { word: 'Rice', definition: 'A grain that is a staple food in Asia' },
  { word: 'Meat', definition: 'Animal flesh used as food' },
  { word: 'Salt', definition: 'White crystals used to season food' },
  { word: 'Sugar', definition: 'Sweet white crystals used in cooking' },
  { word: 'Tea', definition: 'A hot drink made by steeping leaves' },
  { word: 'Soap', definition: 'A substance used for washing and cleaning' },
  { word: 'Door', definition: 'A hinged barrier used to close an opening' },
  { word: 'Window', definition: 'An opening in a wall that lets in light' },
  { word: 'Chair', definition: 'A piece of furniture for sitting on' },
  { word: 'Table', definition: 'A piece of furniture with a flat top' },
  { word: 'Bed', definition: 'A piece of furniture for sleeping on' },
  { word: 'Shoe', definition: 'Footwear that protects your foot' },
  { word: 'Shirt', definition: 'A garment worn on the upper body' },
  { word: 'Phone', definition: 'A device used for making calls' },
  { word: 'Clock', definition: 'A device that shows the time' },
  { word: 'Pen', definition: 'A tool used for writing with ink' },
  { word: 'Bag', definition: 'A container made of flexible material' },
]

export const WORD_MATCH_MEDIUM: WordPair[] = [
  { word: 'Eloquent', definition: 'Fluent and persuasive in speaking or writing' },
  { word: 'Benevolent', definition: 'Well-meaning and kindly in nature' },
  { word: 'Ephemeral', definition: 'Lasting for a very short time' },
  { word: 'Ubiquitous', definition: 'Present or found everywhere at once' },
  { word: 'Serendipity', definition: 'The occurrence of happy events by chance' },
  { word: 'Resilience', definition: 'The ability to recover quickly from difficulties' },
  { word: 'Meticulous', definition: 'Showing great attention to every detail' },
  { word: 'Pragmatic', definition: 'Dealing with things in a practical way' },
  { word: 'Ambiguous', definition: 'Open to more than one interpretation' },
  { word: 'Candid', definition: 'Truthful and straightforward in speech' },
  { word: 'Diligent', definition: 'Having careful and persistent effort' },
  { word: 'Empathy', definition: 'The ability to understand others feelings' },
  { word: 'Flourish', definition: 'To grow or develop in a healthy way' },
  { word: 'Genuine', definition: 'Truly what it is claimed to be' },
  { word: 'Harmony', definition: 'A pleasing arrangement of parts' },
  { word: 'Inevitable', definition: 'Certain to happen and unavoidable' },
  { word: 'Jovial', definition: 'Cheerful and friendly in manner' },
  { word: 'Knowledge', definition: 'Facts and information acquired through experience' },
  { word: 'Luminous', definition: 'Giving off or reflecting bright light' },
  { word: 'Majestic', definition: 'Having impressive beauty or dignity' },
  { word: 'Nostalgia', definition: 'A sentimental longing for the past' },
  { word: 'Opulent', definition: 'Ostentatiously rich and luxurious' },
  { word: 'Persevere', definition: 'To continue despite difficulty or delay' },
  { word: 'Quintessential', definition: 'Representing the most perfect example' },
  { word: 'Radiant', definition: 'Sending out light; shining brightly' },
  { word: 'Spectrum', definition: 'A wide range of related qualities' },
  { word: 'Tenacious', definition: 'Holding firmly to something; persistent' },
  { word: 'Unique', definition: 'Being the only one of its kind' },
  { word: 'Vivid', definition: 'Producing powerful feelings or clear images' },
  { word: 'Wanderlust', definition: 'A strong desire to travel and explore' },
  { word: 'Xenial', definition: 'Friendly to visitors or guests' },
  { word: 'Yearning', definition: 'A feeling of intense longing for something' },
  { word: 'Zealous', definition: 'Having great energy or enthusiasm' },
  { word: 'Brevity', definition: 'Concise and exact use of words' },
  { word: 'Curiosity', definition: 'A strong desire to know or learn' },
  { word: 'Dexterity', definition: 'Skill in performing tasks with hands' },
  { word: 'Endeavor', definition: 'An attempt to achieve a goal' },
  { word: 'Fortitude', definition: 'Courage in pain or adversity' },
  { word: 'Gratitude', definition: 'The quality of being thankful' },
  { word: 'Hypothesis', definition: 'A proposed explanation for a phenomenon' },
]

export const WORD_MATCH_HARD: WordPair[] = [
  { word: 'Acrophobia', definition: 'An extreme or irrational fear of heights' },
  { word: 'Belligerent', definition: 'Hostile and aggressive in behavior' },
  { word: 'Cacophony', definition: 'A harsh mixture of sounds' },
  { word: 'Debacle', definition: 'A sudden and ignominious failure' },
  { word: 'Eccentric', definition: 'Unconventional and slightly strange behavior' },
  { word: 'Fastidious', definition: 'Very attentive to accuracy and detail' },
  { word: 'Gregarious', definition: 'Fond of company; sociable in nature' },
  { word: 'Hedonistic', definition: 'Engaged in the pursuit of pleasure' },
  { word: 'Idiosyncratic', definition: 'Relating to distinctive peculiar characteristics' },
  { word: 'Juxtapose', definition: 'To place close together for contrasting effect' },
  { word: 'Kowtow', definition: 'To act in an excessively subservient manner' },
  { word: 'Languid', definition: 'Displaying a disinclination for physical exertion' },
  { word: 'Magnanimous', definition: 'Very generous or forgiving toward a rival' },
  { word: 'Nefarious', definition: 'Wicked or criminal in nature' },
  { word: 'Obsequious', definition: 'Obedient or attentive to an excessive degree' },
  { word: 'Pernicious', definition: 'Having a harmful effect especially gradually' },
  { word: 'Querulous', definition: 'Complaining in a petulant or whining manner' },
  { word: 'Recalcitrant', definition: 'Having an obstinately uncooperative attitude' },
  { word: 'Surreptitious', definition: 'Kept secret especially because it would not be approved' },
  { word: 'Truculent', definition: 'Eager or quick to argue or fight' },
  { word: 'Ubiquity', definition: 'The fact of appearing everywhere at the same time' },
  { word: 'Vicissitude', definition: 'A change of circumstances usually unwelcome' },
  { word: 'Whimsical', definition: 'Playfully quaint or fanciful especially in an appealing way' },
  { word: 'Xenophobic', definition: 'Having a dislike of or prejudice against people from other countries' },
  { word: 'Yielding', definition: 'Giving way to pressure or influence' },
  { word: 'Zealotry', definition: 'Fanatical and uncompromising pursuit of ideals' },
  { word: 'Aplomb', definition: 'Self-confidence or assurance especially in a demanding situation' },
  { word: 'Bemused', definition: 'Puzzled or confused especially by something unexpected' },
  { word: 'Clandestine', definition: 'Kept secret or done secretively' },
  { word: 'Dearth', definition: 'A scarcity or lack of something needed' },
  { word: 'Ennui', definition: 'A feeling of listlessness arising from lack of occupation' },
  { word: 'Facetious', definition: 'Treating serious issues with deliberately inappropriate humor' },
  { word: 'Grandiose', definition: 'Impressive or magnificent in appearance or style' },
  { word: 'Harbinger', definition: 'A person or thing that announces the approach of another' },
  { word: 'Impetuous', definition: 'Acting quickly without thought or care' },
  { word: 'Laconic', definition: 'Using very few words in speech or writing' },
  { word: 'Misanthrope', definition: 'A person who dislikes humankind and avoids society' },
  { word: 'Narcissistic', definition: 'Having an excessive interest in ones own appearance' },
  { word: 'Ostentatious', definition: 'Characterized by vulgar or pretentious display' },
  { word: 'Parsimonious', definition: 'Unwilling to spend money or use resources' },
]

export const WORD_MATCH_EXPERT: WordPair[] = [
  { word: 'Pneumonoultramicroscopicsilicovolcanoconiosis', definition: 'A lung disease caused by inhaling very fine silica dust' },
  { word: 'Hippopotomonstrosesquipedaliophobia', definition: 'The irrational fear of long words' },
  { word: 'Supercalifragilisticexpialidocious', definition: 'Extraordinarily good; wonderful (popularized by Mary Poppins)' },
  { word: 'Pseudopseudohypoparathyroidism', definition: 'An inherited disorder resembling pseudohypoparathyroidism' },
  { word: 'Floccinaucinihilipilification', definition: 'The action of estimating something as worthless' },
  { word: 'Antidisestablishmentarianism', definition: 'Opposition to withdrawal of state support from established church' },
  { word: 'Honorificabilitudinitatibus', definition: 'The state of being able to achieve honors; longest word with alternating vowels/consonants' },
  { word: 'Incomprehensibilities', definition: 'Things that are impossible to understand or comprehend' },
  { word: 'Unconstitutionally', definition: 'In a manner that violates the constitution' },
  { word: 'Electrocardiograms', definition: 'Recordings of the electrical activity of the heart' },
  { word: 'Psychopharmacology', definition: 'The study of the effect of drugs on the mind and behavior' },
  { word: 'Otorhinolaryngology', definition: 'The branch of medicine dealing with ears nose and throat' },
  { word: 'Gastroenterologist', definition: 'A doctor specializing in the digestive system' },
  { word: 'Hepaticopancreatobiliary', definition: 'Relating to the liver pancreas and biliary system' },
  { word: 'Immunohistochemistry', definition: 'A technique using antibodies to detect antigens in tissue' },
  { word: 'Laryngotracheobronchitis', definition: 'Inflammation of the larynx trachea and bronchi; also called croup' },
  { word: 'Methylenedioxymethamphetamine', definition: 'The chemical name for the drug commonly known as ecstasy' },
  { word: 'Radioimmunoelectrophoresis', definition: 'A technique combining radioimmunoassay and electrophoresis' },
  { word: 'Spectrophotometrically', definition: 'In a manner relating to measurement of light intensity at different wavelengths' },
  { word: 'Thermodynamically', definition: 'In a manner relating to the branch of physics dealing with heat and energy' },
  { word: 'Ultramicroscopically', definition: 'At a scale too small to be seen with a regular microscope' },
  { word: 'Volcanological', definition: 'Relating to the scientific study of volcanoes' },
  { word: 'Xeroradiographically', definition: 'In a manner relating to a type of xerographic imaging' },
  { word: 'Yttriumaluminumgarnet', definition: 'A synthetic crystalline compound used in lasers' },
  { word: 'Zymopharmacological', definition: 'Relating to the study of enzymes and their pharmacological effects' },
  { word: 'Archaeoastronomical', definition: 'Relating to the study of ancient astronomy' },
  { word: 'Bioelectromagnetics', definition: 'The study of electromagnetic phenomena in biological systems' },
  { word: 'Cholecystokinin', definition: 'A hormone that stimulates digestion and appetite' },
  { word: 'Deoxyribonucleotide', definition: 'A nucleotide containing deoxyribose found in DNA' },
  { word: 'Electroencephalography', definition: 'The recording of electrical activity of the brain' },
  { word: 'Fluoroantimonic', definition: 'Relating to the strongest known superacid' },
  { word: 'Glucuronidation', definition: 'A metabolic process for eliminating substances from the body' },
  { word: 'Hematopoiesis', definition: 'The formation of blood cellular components' },
  { word: 'Immunoelectrophoresis', definition: 'A technique combining electrophoresis and immunodiffusion' },
  { word: 'Kymographically', definition: 'In a manner relating to recording physiological movements' },
  { word: 'Laparoscopically', definition: 'In a manner relating to minimally invasive abdominal surgery' },
  { word: 'Microphotographically', definition: 'In a manner relating to photographing at very small scale' },
  { word: 'Neurophysiological', definition: 'Relating to the function of the nervous system' },
  { word: 'Ophthalmologically', definition: 'In a manner relating to the study of eye diseases' },
  { word: 'Pharmacotherapeutic', definition: 'Relating to the use of drugs in treating disease' },
]

// ==================== WORD SCRAMBLE / SPELLING BEE / ANAGRAMS WORD BANK ====================

export const SPELLING_EASY: WordWithHint[] = [
  { word: 'CAT', hint: 'A small furry pet that purrs' },
  { word: 'DOG', hint: 'A loyal pet that barks' },
  { word: 'SUN', hint: 'Gives us light during the day' },
  { word: 'RUN', hint: 'To move quickly on foot' },
  { word: 'BIG', hint: 'Large in size' },
  { word: 'BAT', hint: 'A flying mammal active at night' },
  { word: 'CUP', hint: 'A container for drinking' },
  { word: 'HAT', hint: 'Worn on your head' },
  { word: 'PEN', hint: 'Used for writing' },
  { word: 'MAP', hint: 'Shows locations and directions' },
  { word: 'BOX', hint: 'A container with sides' },
  { word: 'CAR', hint: 'A vehicle with four wheels' },
  { word: 'BUS', hint: 'Public transportation for many people' },
  { word: 'KEY', hint: 'Used to unlock doors' },
  { word: 'MUG', hint: 'A cup with a handle' },
  { word: 'PAN', hint: 'Used for cooking on a stove' },
  { word: 'JAM', hint: 'A sweet spread made from fruit' },
  { word: 'ICE', hint: 'Frozen water' },
  { word: 'JET', hint: 'A fast aircraft' },
  { word: 'LIP', hint: 'Part of your mouth' },
  { word: 'NET', hint: 'Used for catching fish or balls' },
  { word: 'OWL', hint: 'A nocturnal bird of prey' },
  { word: 'PIE', hint: 'A baked dish with filling' },
  { word: 'RAT', hint: 'A rodent larger than a mouse' },
  { word: 'TIE', hint: 'Worn around the neck with a suit' },
  { word: 'VAN', hint: 'A medium-sized vehicle' },
  { word: 'WIN', hint: 'To be victorious' },
  { word: 'YAM', hint: 'A starchy root vegetable' },
  { word: 'ZOO', hint: 'Where animals are kept for display' },
  { word: 'ANT', hint: 'A tiny insect that lives in colonies' },
]

export const SPELLING_MEDIUM: WordWithHint[] = [
  { word: 'APPLE', hint: 'A round red or green fruit' },
  { word: 'HOUSE', hint: 'A place where people live' },
  { word: 'WATER', hint: 'Essential for all life' },
  { word: 'SCHOOL', hint: 'A place for learning' },
  { word: 'FRIEND', hint: 'Someone you trust and enjoy' },
  { word: 'BRIDGE', hint: 'Structure built over a river' },
  { word: 'CANDLE', hint: 'Produces light from a flame' },
  { word: 'DINNER', hint: 'The evening meal' },
  { word: 'FLOWER', hint: 'The colorful part of a plant' },
  { word: 'GARDEN', hint: 'An area for growing plants' },
  { word: 'HUNTER', hint: 'Someone who tracks and catches animals' },
  { word: 'JUNGLE', hint: 'A dense tropical forest' },
  { word: 'KITTEN', hint: 'A young cat' },
  { word: 'LANTERN', hint: 'A portable light source' },
  { word: 'MIRROR', hint: 'Reflects your image' },
  { word: 'NATURE', hint: 'The natural world around us' },
  { word: 'ORANGE', hint: 'A citrus fruit and a color' },
  { word: 'PENCIL', hint: 'Used for writing and drawing' },
  { word: 'QUILT', hint: 'A warm bed covering' },
  { word: 'RABBIT', hint: 'A small furry animal with long ears' },
  { word: 'SPIDER', hint: 'An eight-legged creature' },
  { word: 'TIGER', hint: 'A large striped wild cat' },
  { word: 'UMBRELLA', hint: 'Keeps you dry in the rain' },
  { word: 'VILLAGE', hint: 'A small community in the countryside' },
  { word: 'WINTER', hint: 'The coldest season of the year' },
  { word: 'YELLOW', hint: 'The color of the sun' },
  { word: 'ZEBRA', hint: 'A striped African animal' },
  { word: 'BASKET', hint: 'A woven container for carrying things' },
  { word: 'CASTLE', hint: 'A large fortified building from medieval times' },
  { word: 'DONKEY', hint: 'An animal similar to a small horse' },
  { word: 'FATHER', hint: 'A male parent' },
  { word: 'GUITAR', hint: 'A stringed musical instrument' },
  { word: 'HAMMER', hint: 'A tool for driving nails' },
  { word: 'ISLAND', hint: 'Land surrounded by water' },
  { word: 'JACKET', hint: 'A short coat worn on the upper body' },
  { word: 'KITCHEN', hint: 'Room where food is prepared' },
  { word: 'LEMON', hint: 'A sour yellow citrus fruit' },
  { word: 'MONKEY', hint: 'A primate known for swinging from trees' },
  { word: 'NAPKIN', hint: 'Used to wipe your mouth while eating' },
  { word: 'OCEAN', hint: 'A vast body of salt water' },
]

export const SPELLING_HARD: WordWithHint[] = [
  { word: 'ELEPHANT', hint: 'The largest land animal with a trunk' },
  { word: 'COMPUTER', hint: 'Electronic device for processing data' },
  { word: 'BUTTERFLY', hint: 'A colorful insect with wings' },
  { word: 'ADVENTURE', hint: 'An exciting or unusual experience' },
  { word: 'MOUNTAIN', hint: 'A very tall natural landform' },
  { word: 'CHOCOLATE', hint: 'A sweet treat made from cacao' },
  { word: 'DINOSAUR', hint: 'Ancient reptiles that are now extinct' },
  { word: 'ELEPHANT', hint: 'Large gray animal with a long trunk' },
  { word: 'FIREWORK', hint: 'Explosive display of light and color' },
  { word: 'GIRAFFE', hint: 'Tall African animal with a long neck' },
  { word: 'HURRICANE', hint: 'A powerful tropical storm' },
  { word: 'IGLOO', hint: 'A dome-shaped shelter made of ice blocks' },
  { word: 'JOURNEY', hint: 'An act of traveling from one place to another' },
  { word: 'KNIGHT', hint: 'A medieval warrior in armor' },
  { word: 'LABYRINTH', hint: 'A complex maze-like structure' },
  { word: 'MOUNTAIN', hint: 'A large natural elevation of the earth' },
  { word: 'NECKLACE', hint: 'Jewelry worn around the neck' },
  { word: 'ORPHAN', hint: 'A child whose parents are deceased' },
  { word: 'PENGUIN', hint: 'A flightless bird that lives in cold climates' },
  { word: 'QUESTION', hint: 'A sentence asking for information' },
  { word: 'RAINBOW', hint: 'Colorful arc in the sky after rain' },
  { word: 'SANDWICH', hint: 'Food between two slices of bread' },
  { word: 'THUNDER', hint: 'The sound that follows lightning' },
  { word: 'UNICORN', hint: 'A mythical horse with a single horn' },
  { word: 'VACATION', hint: 'A period of time spent away from work' },
  { word: 'WATERFALL', hint: 'Water falling from a great height' },
  { word: 'XYLOPHONE', hint: 'A musical instrument with wooden bars' },
  { word: 'YOGURT', hint: 'A fermented dairy product' },
  { word: 'ZEPPELIN', hint: 'A large rigid airship' },
  { word: 'BIRTHDAY', hint: 'The anniversary of ones birth' },
  { word: 'CAMERA', hint: 'A device for taking photographs' },
  { word: 'DIAMOND', hint: 'A precious gemstone made of carbon' },
  { word: 'ELEVATOR', hint: 'A platform for moving between floors' },
  { word: 'FOREST', hint: 'A large area covered with trees' },
  { word: 'GLACIER', hint: 'A large persistent body of ice' },
  { word: 'HOSPITAL', hint: 'A place where sick people receive treatment' },
  { word: 'INSECT', hint: 'A small creature with six legs' },
  { word: 'JUPITER', hint: 'The largest planet in our solar system' },
  { word: 'KANGAROO', hint: 'A hopping marsupial from Australia' },
  { word: 'LEOPARD', hint: 'A big cat with spotted fur' },
]

export const SPELLING_EXPERT: WordWithHint[] = [
  { word: 'ANTIDISESTABLISHMENTARIANISM', hint: 'Opposition to withdrawing state support from an established church' },
  { word: 'FLOCCINAUCINIHILIPILIFICATION', hint: 'The act of describing something as worthless' },
  { word: 'PSEUDOPSEUDOHYPOPARATHYROIDISM', hint: 'An inherited disorder' },
  { word: 'HONORIFICABILITUDINITATIBUS', hint: 'The state of being able to achieve honors' },
  { word: 'INCOMPREHENSIBILITIES', hint: 'Things that cannot be understood' },
  { word: 'SUPERCALIFRAGILISTICEXPIALIDOCIOUS', hint: 'Extraordinarily good; used in Mary Poppins' },
  { word: 'HIPPOPOTOMONSTROSESQUIPPEDALIOPHOBIA', hint: 'Fear of long words' },
  { word: 'PNEUMONOULTRAMICROSCOPICSILICOVOLCANOCONIOSIS', hint: 'A lung disease caused by inhaling fine ash' },
  { word: 'DEOXYRIBONUCLEOTIDE', hint: 'A building block of DNA' },
  { word: 'ELECTROENCEPHALOGRAPHY', hint: 'The recording of brain electrical activity' },
  { word: 'GASTROENTEROLOGIST', hint: 'A doctor specializing in the digestive system' },
  { word: 'HEPATICOPANCREATOBILIARY', hint: 'Relating to liver pancreas and biliary system' },
  { word: 'IMMUNOHISTOCHEMISTRY', hint: 'Using antibodies to detect antigens in tissue' },
  { word: 'LARYNGOTRACHEOBRONCHITIS', hint: 'Inflammation of larynx trachea and bronchi' },
  { word: 'METHYLENEDIOXYMETHAMPHETAMINE', hint: 'The chemical name for ecstasy' },
  { word: 'NEUROPHYSIOLOGICAL', hint: 'Relating to the function of the nervous system' },
  { word: 'OPHTHALMOLOGICALLY', hint: 'Relating to the study of eye diseases' },
  { word: 'PHARMACOTHERAPEUTIC', hint: 'Relating to the use of drugs in treating disease' },
  { word: 'RADIOIMMUNOELECTROPHORESIS', hint: 'A technique combining radioimmunoassay and electrophoresis' },
  { word: 'SPECTROPHOTOMETRICALLY', hint: 'Relating to measurement of light intensity at wavelengths' },
  { word: 'THERMODYNAMICALLY', hint: 'Relating to heat and energy physics' },
  { word: 'ULTRAMICROSCOPICALLY', hint: 'At a scale too small for regular microscopes' },
  { word: 'XYLOGRAPHICALLY', hint: 'In a manner relating to wood engraving' },
  { word: 'ARCHAEOASTRONOMICAL', hint: 'Relating to the study of ancient astronomy' },
  { word: 'BIOELECTROMAGNETICS', hint: 'The study of electromagnetic phenomena in biology' },
  { word: 'CHOLECYSTOKININ', hint: 'A hormone that stimulates digestion' },
  { word: 'DICHLORODIFLUOROMETHANE', hint: 'A chlorofluorocarbon once used as refrigerant' },
  { word: 'ETHYLIDENEDIAMINOBENZENE', hint: 'An organic compound used in dye manufacturing' },
  { word: 'FLUOROANTIMONIC', hint: 'Relating to the strongest known superacid' },
  { word: 'GLUCURONIDATION', hint: 'A metabolic process for eliminating substances' },
  { word: 'HEMATOPOIESIS', hint: 'The formation of blood cellular components' },
  { word: 'IMMUNOELECTROPHORESIS', hint: 'Combining electrophoresis and immunodiffusion' },
  { word: 'KYMGRAPHICALLY', hint: 'Relating to recording physiological movements' },
  { word: 'LAPAROSCOPICALLY', hint: 'Relating to minimally invasive abdominal surgery' },
  { word: 'MICROPHOTOGRAPHICALLY', hint: 'Relating to photographing at very small scale' },
  { word: 'OTORHINOLARYNGOLOGY', hint: 'The branch of medicine for ears nose and throat' },
  { word: 'PSYCHOPHARMACOLOGY', hint: 'The study of drug effects on mind and behavior' },
  { word: 'RADIOTELEGRAPHICALLY', hint: 'Relating to wireless telegraphy' },
  { word: 'THYROPARATHYROIDECTOMIZED', hint: 'Having had thyroid and parathyroid removed' },
  { word: 'UNCONSTITUTIONALLY', hint: 'In a manner violating the constitution' },
]

// ==================== TYPING RACE SENTENCE BANK ====================

export const TYPING_EASY = [
  'The cat sat on the mat.',
  'I love to learn new things.',
  'Practice makes perfect every day.',
  'Coding is fun and rewarding.',
  'Keep going and never give up.',
  'The sun is shining bright today.',
  'She drank a cup of hot tea.',
  'He ran fast to catch the bus.',
  'The dog wagged its happy tail.',
  'Birds sing beautiful songs at dawn.',
  'We went to the park yesterday.',
  'Reading books opens new worlds.',
  'The sky is blue and clear.',
  'She has a red bicycle.',
  'He likes to play the guitar.',
  'The cake tastes very sweet.',
  'They went swimming in the pool.',
  'The flower bloomed in spring.',
  'A rainbow appeared after the rain.',
  'The baby laughed with joy.',
  'We ate dinner at seven.',
  'The moon shines at night.',
  'She wrote a letter to her friend.',
  'He painted the wall blue.',
  'The tree has green leaves.',
  'I enjoy walking in the rain.',
  'The car drove down the road.',
  'She planted seeds in the garden.',
  'The fish swam in the pond.',
  'He built a house of blocks.',
]

export const TYPING_MEDIUM = [
  'The quick brown fox jumps over the lazy dog near the river.',
  'Education is the passport to the future for tomorrow belongs to those who prepare today.',
  'Success is not final, failure is not fatal: it is the courage to continue that counts.',
  'The greatest glory in living lies not in never falling, but in rising every time we fall.',
  'Learning is a treasure that will follow its owner everywhere through life.',
  'The only way to do great work is to love what you do every single day.',
  'Knowledge is power and the ability to share it is a true sign of wisdom.',
  'Every expert was once a beginner who decided to keep practicing consistently.',
  'Reading gives us somewhere to go when we have to stay where we are.',
  'The mind is not a vessel to be filled but a fire to be kindled with curiosity.',
  'Dream is not what you see in sleep, it is the thing that does not let you sleep.',
  'The best time to plant a tree was twenty years ago, the second best time is now.',
  'It does not matter how slowly you go as long as you do not stop moving forward.',
  'A person who never made a mistake never tried anything new or challenging.',
  'The secret of getting ahead is getting started on the path to your goals.',
  'In the middle of difficulty lies opportunity waiting to be discovered and seized.',
  'What we think we become through our actions and the choices we make daily.',
  'The journey of a thousand miles begins with a single step taken with purpose.',
  'To be yourself in a world constantly trying to make you something else is the greatest accomplishment.',
  'Life is what happens when you are busy making other plans for the future.',
  'Happiness is not something ready made, it comes from your own actions and attitude.',
  'The future belongs to those who believe in the beauty of their dreams and work for them.',
  'It is during our darkest moments that we must focus to see the light ahead.',
  'The only impossible journey is the one you never begin to take with courage.',
  'Everything you have ever wanted is sitting on the other side of fear and doubt.',
  'Believe you can and you are already halfway to achieving your greatest goals.',
  'The purpose of our lives is to be happy and spread joy to those around us.',
  'Life shrinks or expands in proportion to ones courage to face new challenges.',
  'If you want to go fast, go alone. If you want to go far, go together with others.',
  'Turn your wounds into wisdom and use your past experiences to help others today.',
]

export const TYPING_HARD = [
  'The quintessential zebra zigzagged zealously through the zoo while visitors watched with wonder.',
  'Programming requires persistent practice, profound patience, and perpetual problem-solving prowess.',
  'Innovation distinguishes between a leader and a follower in the rapidly evolving technological landscape.',
  'To be or not to be, that is the question whether tis nobler in the mind to suffer.',
  'The quick brown fox jumps over the lazy dog while the wolf watches from the hilltop.',
  'Philosophical contemplation often leads to profound insights about the nature of existence and consciousness.',
  'Extraordinary achievements require extraordinary dedication and an unwavering commitment to excellence.',
  'Contemporary architecture seamlessly blends modern aesthetics with traditional building techniques.',
  'Interdisciplinary research methodologies foster groundbreaking discoveries across multiple academic domains.',
  'Sustainable agricultural practices are essential for maintaining ecological balance and food security.',
  'The juxtaposition of ancient traditions and modern technology creates fascinating cultural dynamics.',
  'Psychological resilience enables individuals to navigate through adversity with grace and determination.',
  'Mathematical theorems provide elegant solutions to complex problems in theoretical physics.',
  'The proliferation of digital communication has fundamentally transformed human social interactions.',
  'Archaeological excavations continuously reveal surprising insights about ancient civilizations.',
  'Environmental conservation efforts require collective action and sustained commitment from all nations.',
  'Neuroscientific research continues to unravel the mysteries of human cognition and behavior.',
  'Artificial intelligence is revolutionizing industries from healthcare to transportation and beyond.',
  'The symphony of orchestral instruments created a breathtaking auditory experience for the audience.',
  'Meteorological phenomena such as hurricanes demonstrate the immense power of natural forces.',
  'Entrepreneurial ventures demand strategic planning, risk assessment, and adaptability in dynamic markets.',
  'Linguistic diversity enriches human culture and preserves unique worldviews across generations.',
  'The evolution of democratic institutions reflects humanity ongoing quest for freedom and justice.',
  'Photovoltaic technology harnesses solar energy to generate clean electricity for sustainable development.',
  'Astronomical observations through advanced telescopes expand our understanding of the cosmos.',
  'Biotechnological innovations offer promising solutions to global health challenges and diseases.',
  'The convergence of art and science produces remarkable achievements in creative expression.',
  'Philanthropic initiatives address societal inequalities and empower marginalized communities worldwide.',
  'Culinary traditions reflect the rich tapestry of cultural heritage and regional ingredients.',
  'Oceanographic expeditions explore the deepest trenches and discover previously unknown marine species.',
]

export const TYPING_EXPERT = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  'The antidisestablishmentarianistic propensities of the counterrevolutionaries were comprehensively elucidated by scholars.',
  'Floccinaucinihilipilification is the estimation of something as worthless, which ironically takes quite a long word to describe.',
  'Pseudopseudohypoparathyroidism is an inherited disorder that mimics but is not actually pseudohypoparathyroidism at all.',
  'Supercalifragilisticexpialidocious, although nonsensical in meaning, is remarkably difficult to type correctly and quickly.',
  'Pneumonoultramicroscopicsilicovolcanoconiosis is the longest word found in major English dictionaries and medical literature.',
  'Hippopotomonstrosesquipedaliophobia is ironically the name given to the fear of long words by psychologists.',
  'Honorificabilitudinitatibus remains the longest English word with alternating consonants and vowels throughout.',
  'The electroencephalographic measurements revealed unprecedented patterns of neural activity during deep meditation.',
  'Immunohistochemical analysis demonstrated significant expression of biomarkers in the tissue samples collected.',
  'Gastroenterological research has advanced significantly with the development of minimally invasive diagnostic techniques.',
  'Otorhinolaryngological procedures have become increasingly sophisticated with robotic surgical assistance.',
  'Psychopharmacological interventions must be carefully monitored to ensure optimal therapeutic outcomes.',
  'The thermodynamically unfavorable reaction was driven forward by coupling it with an exergonic process.',
  'Spectrophotometrically determined concentrations confirmed the hypothesis regarding chemical composition.',
  'Radioimmunoelectrophoretic separation allowed precise identification of the target protein fractions.',
  'Laparoscopically guided surgical procedures minimize patient recovery time and reduce postoperative complications.',
  'The archaeoastronomical evidence suggests ancient civilizations possessed sophisticated celestial knowledge.',
  'Bioelectromagnetic phenomena in living organisms continue to fascinate researchers in the field of biophysics.',
  'Deoxyribonucleotide sequences were analyzed using next-generation sequencing technologies.',
  'The hepaticopancreatobiliary system plays a crucial role in digestion and metabolic homeostasis.',
  'Methylenedioxymethamphetamine has been studied for its potential therapeutic applications in psychotherapy.',
  'Immunoelectrophoretic techniques remain valuable tools in clinical diagnostic laboratories worldwide.',
  'Microphotographically documented specimens provide permanent records of microscopic structures.',
  'The cholecystokinin hormone regulates appetite and stimulates the release of digestive enzymes.',
  'Glucuronidation is an important phase two metabolic pathway for drug detoxification.',
  'Hematopoiesis occurs primarily in the bone marrow and produces all blood cell types.',
  'Neurophysiological studies have mapped complex neural circuits underlying various cognitive functions.',
  'Pharmacotherapeutic approaches continue to evolve with our expanding understanding of molecular pathways.',
  'The ultramicroscopically resolved images revealed subcellular structures never before observed.',
]

// ==================== QUIZ RACE QUESTION BANK ====================

export interface QuizQuestion {
  question: string
  options: string[]
  correctAnswer: number
  hint?: string
}

export const QUIZ_EASY: QuizQuestion[] = [
  { question: 'What is the capital of France?', options: ['London', 'Berlin', 'Paris', 'Madrid'], correctAnswer: 2, hint: 'City of Light' },
  { question: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], correctAnswer: 1, hint: 'Named after Roman god of war' },
  { question: 'What is H2O?', options: ['Oxygen', 'Hydrogen', 'Water', 'Salt'], correctAnswer: 2, hint: 'Essential for life' },
  { question: 'How many continents are there?', options: ['5', '6', '7', '8'], correctAnswer: 2, hint: 'Includes Africa, Asia, Europe...' },
  { question: 'What gas do plants absorb?', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'], correctAnswer: 2, hint: 'CO2' },
  { question: 'Which animal is known as the King of the Jungle?', options: ['Tiger', 'Elephant', 'Lion', 'Bear'], correctAnswer: 2, hint: 'Has a majestic mane' },
  { question: 'What color are bananas when ripe?', options: ['Red', 'Yellow', 'Green', 'Blue'], correctAnswer: 1, hint: 'A bright sunny color' },
  { question: 'How many legs does a spider have?', options: ['6', '8', '10', '4'], correctAnswer: 1, hint: 'More than an insect' },
  { question: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correctAnswer: 3, hint: 'Between Asia and Americas' },
  { question: 'Which is the smallest prime number?', options: ['0', '1', '2', '3'], correctAnswer: 2, hint: 'The only even prime' },
  { question: 'What do bees produce?', options: ['Milk', 'Honey', 'Silk', 'Wool'], correctAnswer: 1, hint: 'Sweet and golden' },
  { question: 'Which season is the coldest?', options: ['Summer', 'Spring', 'Autumn', 'Winter'], correctAnswer: 3, hint: 'Snow falls during this time' },
  { question: 'What is the boiling point of water?', options: ['50C', '100C', '150C', '200C'], correctAnswer: 1, hint: 'At sea level' },
  { question: 'Which fruit has seeds on the outside?', options: ['Apple', 'Banana', 'Strawberry', 'Grape'], correctAnswer: 2, hint: 'Red and heart-shaped' },
  { question: 'How many days are in a week?', options: ['5', '6', '7', '8'], correctAnswer: 2, hint: 'Monday to Sunday' },
  { question: 'What is the currency of the USA?', options: ['Euro', 'Pound', 'Dollar', 'Yen'], correctAnswer: 2, hint: 'Symbol is $' },
  { question: 'Which organ pumps blood?', options: ['Brain', 'Liver', 'Heart', 'Lung'], correctAnswer: 2, hint: 'Beats continuously' },
  { question: 'What is frozen water called?', options: ['Steam', 'Ice', 'Snow', 'Frost'], correctAnswer: 1, hint: 'Solid state of water' },
  { question: 'Which bird cannot fly?', options: ['Eagle', 'Penguin', 'Sparrow', 'Hawk'], correctAnswer: 1, hint: 'Lives in cold climates' },
  { question: 'What shape has three sides?', options: ['Square', 'Circle', 'Triangle', 'Rectangle'], correctAnswer: 2, hint: 'Tri- means three' },
  { question: 'Which planet is closest to the Sun?', options: ['Venus', 'Mercury', 'Earth', 'Mars'], correctAnswer: 1, hint: 'Smallest planet' },
  { question: 'What do caterpillars turn into?', options: ['Spiders', 'Butterflies', 'Beetles', 'Bees'], correctAnswer: 1, hint: 'Beautiful winged insects' },
  { question: 'How many hours in a day?', options: ['12', '20', '24', '48'], correctAnswer: 2, hint: 'Half of 48' },
  { question: 'What is the opposite of hot?', options: ['Warm', 'Cool', 'Cold', 'Mild'], correctAnswer: 2, hint: 'Temperature below freezing' },
  { question: 'Which language has the most native speakers?', options: ['English', 'Spanish', 'Mandarin', 'Hindi'], correctAnswer: 2, hint: 'Most spoken in China' },
  { question: 'What is the hardest natural substance?', options: ['Gold', 'Iron', 'Diamond', 'Platinum'], correctAnswer: 2, hint: 'Used in jewelry' },
  { question: 'Which animal is the tallest?', options: ['Elephant', 'Giraffe', 'Horse', 'Camel'], correctAnswer: 1, hint: 'Has a very long neck' },
  { question: 'What do you call a baby cat?', options: ['Puppy', 'Kitten', 'Calf', 'Chick'], correctAnswer: 1, hint: 'Sounds like kitchen' },
  { question: 'How many colors in a rainbow?', options: ['5', '6', '7', '8'], correctAnswer: 2, hint: 'ROYGBIV' },
  { question: 'Which instrument has 88 keys?', options: ['Guitar', 'Violin', 'Piano', 'Drums'], correctAnswer: 2, hint: 'A large keyboard instrument' },
]

export const QUIZ_MEDIUM: QuizQuestion[] = [
  { question: 'What is the largest organ in the human body?', options: ['Heart', 'Liver', 'Skin', 'Brain'], correctAnswer: 2, hint: 'It protects your body' },
  { question: 'Which element has the chemical symbol O?', options: ['Gold', 'Oxygen', 'Silver', 'Iron'], correctAnswer: 1, hint: 'We breathe it' },
  { question: 'What is the square root of 64?', options: ['6', '7', '8', '9'], correctAnswer: 2, hint: '8 x 8 = 64' },
  { question: 'Which country has the most population?', options: ['USA', 'India', 'China', 'Indonesia'], correctAnswer: 1, hint: 'Surpassed China in 2023' },
  { question: 'What is the speed of light?', options: ['300,000 km/s', '150,000 km/s', '500,000 km/s', '100,000 km/s'], correctAnswer: 0, hint: 'Approximately 3 x 10^8 m/s' },
  { question: 'Who painted the Mona Lisa?', options: ['Picasso', 'Van Gogh', 'Da Vinci', 'Monet'], correctAnswer: 2, hint: 'Italian Renaissance artist' },
  { question: 'What is the chemical formula for salt?', options: ['NaCl', 'H2O', 'CO2', 'KCl'], correctAnswer: 0, hint: 'Sodium and Chlorine' },
  { question: 'Which planet has the most moons?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], correctAnswer: 1, hint: 'Has over 140 confirmed moons' },
  { question: 'What year did World War II end?', options: ['1943', '1944', '1945', '1946'], correctAnswer: 2, hint: 'Mid 1940s' },
  { question: 'Which vitamin is produced by sunlight?', options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'], correctAnswer: 3, hint: 'Essential for bones' },
  { question: 'What is the currency of Japan?', options: ['Won', 'Yuan', 'Yen', 'Ringgit'], correctAnswer: 2, hint: 'Symbol is ¥' },
  { question: 'Which is the longest river?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correctAnswer: 1, hint: 'Flows through Egypt' },
  { question: 'What is the main gas in Earth atmosphere?', options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'], correctAnswer: 2, hint: 'Makes up about 78%' },
  { question: 'Who wrote Romeo and Juliet?', options: ['Dickens', 'Shakespeare', 'Austen', 'Twain'], correctAnswer: 1, hint: 'Famous English playwright' },
  { question: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], correctAnswer: 2, hint: 'Not the largest city' },
  { question: 'How many bones in the human body?', options: ['186', '196', '206', '216'], correctAnswer: 2, hint: 'More than 200' },
  { question: 'Which metal is liquid at room temperature?', options: ['Gold', 'Mercury', 'Silver', 'Lead'], correctAnswer: 1, hint: 'Used in old thermometers' },
  { question: 'What is the largest desert?', options: ['Sahara', 'Arabian', 'Antarctica', 'Gobi'], correctAnswer: 2, hint: 'It is actually a cold desert' },
  { question: 'Who developed the theory of relativity?', options: ['Newton', 'Einstein', 'Tesla', 'Hawking'], correctAnswer: 1, hint: 'E = mc²' },
  { question: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi'], correctAnswer: 2, hint: 'Produces energy (ATP)' },
  { question: 'Which country gifted the Statue of Liberty?', options: ['England', 'Spain', 'France', 'Germany'], correctAnswer: 2, hint: 'Given to the USA in 1886' },
  { question: 'What is the hardest rock?', options: ['Granite', 'Marble', 'Diamond', 'Quartz'], correctAnswer: 2, hint: 'Rated 10 on Mohs scale' },
  { question: 'Which ocean is the Bermuda Triangle in?', options: ['Pacific', 'Atlantic', 'Indian', 'Arctic'], correctAnswer: 1, hint: 'Between Americas and Europe' },
  { question: 'What is the chemical symbol for Gold?', options: ['Go', 'Gd', 'Au', 'Ag'], correctAnswer: 2, hint: 'From the Latin Aurum' },
  { question: 'Which planet rotates on its side?', options: ['Mars', 'Uranus', 'Neptune', 'Saturn'], correctAnswer: 1, hint: 'Tilted about 98 degrees' },
  { question: 'How many teeth does an adult have?', options: ['28', '30', '32', '34'], correctAnswer: 2, hint: 'Including wisdom teeth' },
  { question: 'What is the study of fossils called?', options: ['Biology', 'Geology', 'Paleontology', 'Archaeology'], correctAnswer: 2, hint: 'Paleo- means ancient' },
  { question: 'Which is the smallest country?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], correctAnswer: 1, hint: 'Located within Rome' },
  { question: 'What force keeps us on the ground?', options: ['Magnetism', 'Friction', 'Gravity', 'Inertia'], correctAnswer: 2, hint: 'Discovered by Newton' },
  { question: 'Which blood type is the universal donor?', options: ['A', 'B', 'AB', 'O'], correctAnswer: 3, hint: 'Can donate to anyone' },
]

export const QUIZ_HARD: QuizQuestion[] = [
  { question: 'What is the capital city of Turkey?', options: ['Istanbul', 'Ankara', 'Izmir', 'Antalya'], correctAnswer: 1, hint: 'Not the largest city' },
  { question: 'Which scientist discovered penicillin?', options: ['Pasteur', 'Fleming', 'Koch', 'Jenner'], correctAnswer: 1, hint: 'Scottish bacteriologist' },
  { question: 'What is the rarest blood type?', options: ['AB-', 'O-', 'B-', 'A-'], correctAnswer: 0, hint: 'Less than 1% of population' },
  { question: 'Which element has atomic number 79?', options: ['Gold', 'Silver', 'Platinum', 'Mercury'], correctAnswer: 0, hint: 'Au on the periodic table' },
  { question: 'In what year was the internet invented?', options: ['1959', '1969', '1979', '1989'], correctAnswer: 1, hint: 'ARPANET was the precursor' },
  { question: 'What is the deepest ocean trench?', options: ['Tonga', 'Mariana', 'Philippine', 'Java'], correctAnswer: 1, hint: 'Located in the Pacific' },
  { question: 'Which organ produces insulin?', options: ['Liver', 'Kidney', 'Pancreas', 'Stomach'], correctAnswer: 2, hint: 'Located behind the stomach' },
  { question: 'What is the most spoken language in South America?', options: ['Spanish', 'Portuguese', 'English', 'French'], correctAnswer: 1, hint: 'Due to Brazil population' },
  { question: 'Who composed the Four Seasons?', options: ['Mozart', 'Bach', 'Vivaldi', 'Beethoven'], correctAnswer: 2, hint: 'Italian Baroque composer' },
  { question: 'What is the chemical formula for sulfuric acid?', options: ['HCl', 'H2SO4', 'HNO3', 'H3PO4'], correctAnswer: 1, hint: 'Contains sulfur' },
  { question: 'Which planet has the Great Red Spot?', options: ['Mars', 'Saturn', 'Jupiter', 'Neptune'], correctAnswer: 2, hint: 'Largest planet in solar system' },
  { question: 'What is the pH of pure water?', options: ['5', '6', '7', '8'], correctAnswer: 2, hint: 'Neutral on the pH scale' },
  { question: 'Who painted Starry Night?', options: ['Monet', 'Van Gogh', 'Renoir', 'Cezanne'], correctAnswer: 1, hint: 'Dutch post-impressionist' },
  { question: 'What is the longest bone in the body?', options: ['Humerus', 'Tibia', 'Femur', 'Fibula'], correctAnswer: 2, hint: 'Located in the thigh' },
  { question: 'Which gas makes up most of the Sun?', options: ['Helium', 'Hydrogen', 'Oxygen', 'Nitrogen'], correctAnswer: 1, hint: 'Lightest element' },
  { question: 'What is the currency of Switzerland?', options: ['Euro', 'Franc', 'Mark', 'Krona'], correctAnswer: 1, hint: 'Also used in Liechtenstein' },
  { question: 'Who wrote The Origin of Species?', options: ['Lamarck', 'Darwin', 'Wallace', 'Mendel'], correctAnswer: 1, hint: 'Theory of natural selection' },
  { question: 'What is the speed of sound in air?', options: ['243 m/s', '343 m/s', '443 m/s', '543 m/s'], correctAnswer: 1, hint: 'About 1,235 km/h' },
  { question: 'Which country has the most time zones?', options: ['Russia', 'USA', 'France', 'China'], correctAnswer: 2, hint: 'Due to overseas territories' },
  { question: 'What is Avogadro number approximately?', options: ['6.022 × 10²³', '3.14 × 10²³', '1.6 × 10²³', '9.8 × 10²³'], correctAnswer: 0, hint: 'Fundamental constant in chemistry' },
  { question: 'Which vitamin deficiency causes scurvy?', options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'], correctAnswer: 2, hint: 'Found in citrus fruits' },
  { question: 'What is the largest moon of Saturn?', options: ['Europa', 'Titan', 'Ganymede', 'Callisto'], correctAnswer: 1, hint: 'Has a thick atmosphere' },
  { question: 'Who invented the World Wide Web?', options: ['Bill Gates', 'Steve Jobs', 'Tim Berners-Lee', 'Vint Cerf'], correctAnswer: 2, hint: 'British computer scientist' },
  { question: 'What is the most abundant element in the universe?', options: ['Oxygen', 'Carbon', 'Helium', 'Hydrogen'], correctAnswer: 3, hint: 'Simplest element' },
  { question: 'Which war was fought between 1914-1918?', options: ['WWII', 'WWI', 'Korean War', 'Vietnam War'], correctAnswer: 1, hint: 'The Great War' },
  { question: 'What is the study of earthquakes called?', options: ['Geology', 'Seismology', 'Volcanology', 'Meteorology'], correctAnswer: 1, hint: 'Seismo- means shake' },
  { question: 'Which element is a liquid at room temperature?', options: ['Bromine', 'Chlorine', 'Iodine', 'Fluorine'], correctAnswer: 0, hint: 'Reddish-brown liquid' },
  { question: 'What is the capital of New Zealand?', options: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'], correctAnswer: 1, hint: 'Located on the North Island' },
  { question: 'Who developed the periodic table?', options: ['Dalton', 'Bohr', 'Mendeleev', 'Rutherford'], correctAnswer: 2, hint: 'Russian chemist' },
  { question: 'What is the smallest unit of matter?', options: ['Molecule', 'Atom', 'Electron', 'Quark'], correctAnswer: 3, hint: 'Subatomic particle' },
]

export const QUIZ_EXPERT: QuizQuestion[] = [
  { question: 'What is the approximate value of Planck constant?', options: ['6.63 × 10⁻³⁴ J·s', '6.63 × 10⁻²⁴ J·s', '6.63 × 10⁻¹⁴ J·s', '6.63 × 10⁻⁴⁴ J·s'], correctAnswer: 0, hint: 'Fundamental to quantum mechanics' },
  { question: 'In what year was the Magna Carta signed?', options: ['1066', '1215', '1492', '1776'], correctAnswer: 1, hint: '13th century England' },
  { question: 'What is the strongest muscle in the human body?', options: ['Masseter', 'Bicep', 'Quadriceps', 'Heart'], correctAnswer: 3, hint: 'It works continuously without rest' },
  { question: 'Which philosopher wrote Critique of Pure Reason?', options: ['Hegel', 'Kant', 'Nietzsche', 'Descartes'], correctAnswer: 1, hint: 'German Enlightenment philosopher' },
  { question: 'What is the half-life of Carbon-14?', options: ['1,730 years', '5,730 years', '10,730 years', '15,730 years'], correctAnswer: 1, hint: 'Used in radiocarbon dating' },
  { question: 'Which treaty ended the Thirty Years War?', options: ['Treaty of Versailles', 'Peace of Westphalia', 'Treaty of Utrecht', 'Congress of Vienna'], correctAnswer: 1, hint: 'Signed in 1648' },
  { question: 'What is the Chandrasekhar limit?', options: ['1.4 solar masses', '2.4 solar masses', '3.4 solar masses', '4.4 solar masses'], correctAnswer: 0, hint: 'Maximum mass of a stable white dwarf' },
  { question: 'Which composer wrote The Art of Fugue?', options: ['Mozart', 'Bach', 'Handel', 'Haydn'], correctAnswer: 1, hint: 'German Baroque master' },
  { question: 'What is the most electronegative element?', options: ['Oxygen', 'Chlorine', 'Fluorine', 'Nitrogen'], correctAnswer: 2, hint: 'Atomic number 9' },
  { question: 'Who proposed the heliocentric model?', options: ['Ptolemy', 'Galileo', 'Copernicus', 'Kepler'], correctAnswer: 2, hint: 'Polish astronomer' },
  { question: 'What is the Riemann Hypothesis about?', options: ['Prime numbers', 'Quantum mechanics', 'Topology', 'Calculus'], correctAnswer: 0, hint: 'Distribution of zeros of zeta function' },
  { question: 'Which enzyme breaks down starch?', options: ['Lipase', 'Protease', 'Amylase', 'Cellulase'], correctAnswer: 2, hint: 'Found in saliva' },
  { question: 'What is the Schwarzschild radius related to?', options: ['Stars', 'Black holes', 'Neutron stars', 'White dwarfs'], correctAnswer: 1, hint: 'Event horizon boundary' },
  { question: 'Who discovered the structure of DNA?', options: ['Mendel', 'Watson and Crick', 'Franklin', 'Darwin'], correctAnswer: 1, hint: 'Double helix model' },
  { question: 'What is the Heisenberg Uncertainty Principle?', options: ['Energy conservation', 'Position and momentum', 'Wave-particle duality', 'Entropy'], correctAnswer: 1, hint: 'Cannot measure both precisely' },
  { question: 'Which war had the Battle of Gettysburg?', options: ['Revolutionary War', 'Civil War', 'WWI', 'WWII'], correctAnswer: 1, hint: 'American conflict 1861-1865' },
  { question: 'What is the Pauli Exclusion Principle?', options: ['No two electrons can have same quantum state', 'Energy is quantized', 'Light is a wave', 'Mass and energy are equivalent'], correctAnswer: 0, hint: 'Fundamental to quantum mechanics' },
  { question: 'Which ancient civilization built Machu Picchu?', options: ['Aztec', 'Maya', 'Inca', 'Olmec'], correctAnswer: 2, hint: 'South American empire' },
  { question: 'What is the Hubble Constant measuring?', options: ['Gravity', 'Universal expansion', 'Light speed', 'Magnetic fields'], correctAnswer: 1, hint: 'Rate of universe expansion' },
  { question: 'Who formulated the laws of planetary motion?', options: ['Newton', 'Galileo', 'Kepler', 'Copernicus'], correctAnswer: 2, hint: 'German astronomer and mathematician' },
  { question: 'What is the Golden Ratio approximately?', options: ['1.414', '1.618', '2.718', '3.142'], correctAnswer: 1, hint: 'Denoted by phi (φ)' },
  { question: 'Which particle is the Higgs boson associated with?', options: ['Gravity', 'Mass', 'Charge', 'Spin'], correctAnswer: 1, hint: 'Gives particles mass' },
  { question: 'What is the K-T boundary?', options: ['Ocean floor', 'Geological layer', 'Atmospheric layer', 'Mantle boundary'], correctAnswer: 1, hint: 'Marks dinosaur extinction' },
  { question: 'Who wrote Principia Mathematica?', options: ['Einstein', 'Newton', 'Galileo', 'Aristotle'], correctAnswer: 1, hint: 'English physicist and mathematician' },
  { question: 'What is the Casimir Effect?', options: ['Quantum vacuum force', 'Magnetic attraction', 'Gravitational pull', 'Electric discharge'], correctAnswer: 0, hint: 'Force between uncharged plates' },
  { question: 'Which element has the most stable isotope?', options: ['Iron-56', 'Lead-208', 'Uranium-238', 'Carbon-12'], correctAnswer: 1, hint: 'End of radioactive decay chains' },
  { question: 'What is the Fermi Paradox about?', options: ['Quantum entanglement', 'Alien life', 'Black holes', 'Time travel'], correctAnswer: 1, hint: 'Where is everybody?' },
  { question: 'Which mathematician proved Fermat Last Theorem?', options: ['Euler', 'Gauss', 'Wiles', 'Ramanujan'], correctAnswer: 2, hint: 'British mathematician, proved in 1994' },
  { question: 'What is the Bekenstein-Hawking formula about?', options: ['Stellar evolution', 'Black hole entropy', 'Cosmic inflation', 'Quantum gravity'], correctAnswer: 1, hint: 'Relates entropy to event horizon area' },
  { question: 'Which ancient library was in Alexandria?', options: ['Library of Pergamon', 'Library of Alexandria', 'Library of Athens', 'Library of Rome'], correctAnswer: 1, hint: 'One of the largest in ancient world' },
]

// ==================== MEMORY FLIP EMOJI BANK ====================

export const MEMORY_EMOJIS_EASY = ['🍎', '🍌', '🍇', '🍉', '🍊', '🍋', '🍓', '🫐']

export const MEMORY_EMOJIS_MEDIUM = ['🍎', '🍌', '🍇', '🍉', '🍊', '🍋', '🍍', '🥭', '🍣', '🍜', '🍰', '🎂', '🍡', '🍦', '🍨', '🍧']

export const MEMORY_EMOJIS_HARD = ['🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐨', '🐯', '🦁', '🐮', '🐷', '🐸', '🐵', '🐔', '🐧', '🐦', '🦆', '🦅', '🦉', '🦇', '🐺', '🐗']

export const MEMORY_EMOJIS_EXPERT = [
  '😀', '😃', '😄', '😁', '😆', '😅', '😂', '🤣', '😊', '😇',
  '🙂', '🙃', '😉', '😌', '😍', '😘', '😗', '😙', '😚', '😋',
  '😛', '😝', '😜', '🤪', '🤨', '🧐', '🤓', '😎', '🤩', '🥳',
  '😏', '😒', '😞', '😔', '😟', '😕', '🙁', '☹️', '😣', '😖',
  '😫', '😩', '🥺', '😢', '😭', '😤', '😠', '😡', '🤬', '🤯',
  '😳', '🥵', '🥶', '😱', '😨', '😰', '😥', '😓', '🤗', '🤔',
  '🤭', '🤫', '🤥', '😶', '😐', '😑', '😬', '🙄', '💯', '🔥',
  '💎', '⚡', '🌟', '💥', '🌈', '☀️', '🌙', '⭐', '🌊', '🍕',
]

