import { VocabSet } from "../types";

/**
 * English A1 Vocabulary - v2 format
 * CEFR: A1 (Beginner)
 * Word difficulty: All EASY (A1 level words)
 */
export const englishA1Data: VocabSet[] = [
  {
    title: "Greetings & Introductions",
    description: "Essential greetings and phrases for introducing yourself",
    level: "A1",
    difficulty: "BEGINNER",
    order: 1,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Hello", definition: "A greeting used when meeting someone", translation: "", partOfSpeech: "interjection", pronunciation: "heh-LOH", exampleSentence: "Hello, how are you?", exampleTranslation: "", synonyms: "Hi, Hey", antonyms: "Goodbye", difficulty: "EASY", languageCode: "en" },
      { word: "Goodbye", definition: "A farewell said when leaving", translation: "", partOfSpeech: "interjection", pronunciation: "good-BYE", exampleSentence: "Goodbye, see you tomorrow!", exampleTranslation: "", synonyms: "Bye, Farewell", antonyms: "Hello", difficulty: "EASY", languageCode: "en" },
      { word: "Good morning", definition: "A greeting used in the morning", translation: "", partOfSpeech: "phrase", pronunciation: "good MOR-ning", exampleSentence: "Good morning, Mrs. Smith!", exampleTranslation: "", synonyms: "Morning", antonyms: "Good night", difficulty: "EASY", languageCode: "en" },
      { word: "Good afternoon", definition: "A greeting used in the afternoon", translation: "", partOfSpeech: "phrase", pronunciation: "good AF-ter-noon", exampleSentence: "Good afternoon, everyone.", exampleTranslation: "", synonyms: "Afternoon", antonyms: "Good morning", difficulty: "EASY", languageCode: "en" },
      { word: "Good evening", definition: "A greeting used in the evening", translation: "", partOfSpeech: "phrase", pronunciation: "good EEV-ning", exampleSentence: "Good evening, welcome to the party.", exampleTranslation: "", synonyms: "Evening", antonyms: "Good morning", difficulty: "EASY", languageCode: "en" },
      { word: "Good night", definition: "A farewell used when someone is going to sleep", translation: "", partOfSpeech: "phrase", pronunciation: "good NYTE", exampleSentence: "Good night, sleep well!", exampleTranslation: "", synonyms: "Sweet dreams", antonyms: "Good morning", difficulty: "EASY", languageCode: "en" },
      { word: "Thank you", definition: "An expression of gratitude", translation: "", partOfSpeech: "phrase", pronunciation: "THANK yoo", exampleSentence: "Thank you for your help.", exampleTranslation: "", synonyms: "Thanks, Appreciate", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Thank you very much", definition: "A strong expression of gratitude", translation: "", partOfSpeech: "phrase", pronunciation: "THANK yoo VER-ee much", exampleSentence: "Thank you very much for the gift!", exampleTranslation: "", synonyms: "Thanks a lot", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Thanks", definition: "A casual expression of gratitude", translation: "", partOfSpeech: "interjection", pronunciation: "thanks", exampleSentence: "Thanks for calling me.", exampleTranslation: "", synonyms: "Cheers, Appreciate", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Please", definition: "Used to make a polite request", translation: "", partOfSpeech: "adverb", pronunciation: "pleez", exampleSentence: "Please pass the salt.", exampleTranslation: "", synonyms: "Kindly", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Sorry", definition: "An apology or expression of regret", translation: "", partOfSpeech: "interjection", pronunciation: "SOR-ee", exampleSentence: "Sorry, I didn't mean to interrupt.", exampleTranslation: "", synonyms: "Apologize, Excuse me", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Excuse me", definition: "A polite phrase to get attention or pass", translation: "", partOfSpeech: "phrase", pronunciation: "ik-SKYOOZ mee", exampleSentence: "Excuse me, where is the library?", exampleTranslation: "", synonyms: "Pardon, Sorry", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Yes", definition: "An affirmative response", translation: "", partOfSpeech: "adverb", pronunciation: "yes", exampleSentence: "Yes, I agree with you.", exampleTranslation: "", synonyms: "Aye, Sure", antonyms: "No", difficulty: "EASY", languageCode: "en" },
      { word: "No", definition: "A negative response", translation: "", partOfSpeech: "adverb", pronunciation: "noh", exampleSentence: "No, I don't want any.", exampleTranslation: "", synonyms: "Nah, Nope", antonyms: "Yes", difficulty: "EASY", languageCode: "en" },
      { word: "Welcome", definition: "To greet or receive someone gladly", translation: "", partOfSpeech: "verb", pronunciation: "WEL-kum", exampleSentence: "Welcome to our home!", exampleTranslation: "", synonyms: "Greet", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "My name is", definition: "Used to introduce yourself", translation: "", partOfSpeech: "phrase", pronunciation: "my naym iz", exampleSentence: "My name is John.", exampleTranslation: "", synonyms: "I am", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "I am", definition: "The verb to be used in self-introduction", translation: "", partOfSpeech: "phrase", pronunciation: "I am", exampleSentence: "I am a student.", exampleTranslation: "", synonyms: "I'm", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Nice to meet you", definition: "A polite greeting when meeting someone", translation: "", partOfSpeech: "phrase", pronunciation: "nyes too meet yoo", exampleSentence: "Nice to meet you, I'm Sarah.", exampleTranslation: "", synonyms: "Pleased to meet you", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "How are you?", definition: "A question asking about someone's wellbeing", translation: "", partOfSpeech: "phrase", pronunciation: "how ar yoo", exampleSentence: "How are you today?", exampleTranslation: "", synonyms: "How's it going?", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "I'm fine", definition: "A response indicating wellbeing", translation: "", partOfSpeech: "phrase", pronunciation: "aim fayn", exampleSentence: "I'm fine, thank you.", exampleTranslation: "", synonyms: "I'm good", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "See you later", definition: "A casual farewell", translation: "", partOfSpeech: "phrase", pronunciation: "see yoo LAY-ter", exampleSentence: "See you later!", exampleTranslation: "", synonyms: "Catch you later", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "See you soon", definition: "A farewell indicating quick reunion", translation: "", partOfSpeech: "phrase", pronunciation: "see yoo soorn", exampleSentence: "See you soon!", exampleTranslation: "", synonyms: "Talk to you later", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Have a nice day", definition: "A wish for someone's pleasant day", translation: "", partOfSpeech: "phrase", pronunciation: "hav a nay day", exampleSentence: "Have a nice day!", exampleTranslation: "", synonyms: "Take care", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "What is your name?", definition: "A question asking for someone's name", translation: "", partOfSpeech: "phrase", pronunciation: "wot iz yor naym", exampleSentence: "What is your name?", exampleTranslation: "", synonyms: "May I know your name?", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Where are you from?", definition: "A question asking about someone's origin", translation: "", partOfSpeech: "phrase", pronunciation: "wair ar yoo from", exampleSentence: "Where are you from?", exampleTranslation: "", synonyms: "Where do you come from?", antonyms: "", difficulty: "EASY", languageCode: "en" },
    ]
  },
  {
    title: "Numbers & Time",
    description: "Basic numbers, days, months, and time expressions",
    level: "A1",
    difficulty: "BEGINNER",
    order: 2,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "One", definition: "The number 1", translation: "", partOfSpeech: "number", pronunciation: "wun", exampleSentence: "I have one apple.", exampleTranslation: "", synonyms: "1", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Two", definition: "The number 2", translation: "", partOfSpeech: "number", pronunciation: "too", exampleSentence: "Two plus two is four.", exampleTranslation: "", synonyms: "2", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Three", definition: "The number 3", translation: "", partOfSpeech: "number", pronunciation: "three", exampleSentence: "I have three friends.", exampleTranslation: "", synonyms: "3", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Four", definition: "The number 4", translation: "", partOfSpeech: "number", pronunciation: "for", exampleSentence: "There are four seasons.", exampleTranslation: "", synonyms: "4", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Five", definition: "The number 5", translation: "", partOfSpeech: "number", pronunciation: "fayv", exampleSentence: "I have five fingers.", exampleTranslation: "", synonyms: "5", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Six", definition: "The number 6", translation: "", partOfSpeech: "number", pronunciation: "siks", exampleSentence: "Six o'clock.", exampleTranslation: "", synonyms: "6", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Seven", definition: "The number 7", translation: "", partOfSpeech: "number", pronunciation: "SEV-en", exampleSentence: "Seven days in a week.", exampleTranslation: "", synonyms: "7", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Eight", definition: "The number 8", translation: "", partOfSpeech: "number", pronunciation: "ayt", exampleSentence: "Eight plus two is ten.", exampleTranslation: "", synonyms: "8", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Nine", definition: "The number 9", translation: "", partOfSpeech: "number", pronunciation: "nyn", exampleSentence: "Nine months in pregnancy.", exampleTranslation: "", synonyms: "9", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Ten", definition: "The number 10", translation: "", partOfSpeech: "number", pronunciation: "ten", exampleSentence: "Ten fingers on two hands.", exampleTranslation: "", synonyms: "10", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "First", definition: "Coming before all others", translation: "", partOfSpeech: "adjective", pronunciation: "ferst", exampleSentence: "She came in first place.", exampleTranslation: "", synonyms: "Number one", antonyms: "Last", difficulty: "EASY", languageCode: "en" },
      { word: "Second", definition: "Coming after the first", translation: "", partOfSpeech: "adjective", pronunciation: "SEK-und", exampleSentence: "He was second in the race.", exampleTranslation: "", synonyms: "Next", antonyms: "First", difficulty: "EASY", languageCode: "en" },
      { word: "Third", definition: "Coming after the second", translation: "", partOfSpeech: "adjective", pronunciation: "therd", exampleSentence: "Third time is the charm.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Monday", definition: "The first day of the week", translation: "", partOfSpeech: "noun", pronunciation: "MUN-day", exampleSentence: "I work on Monday.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Tuesday", definition: "The second day of the week", translation: "", partOfSpeech: "noun", pronunciation: "TYOOZ-day", exampleSentence: "Tuesday comes after Monday.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Wednesday", definition: "The third day of the week", translation: "", partOfSpeech: "noun", pronunciation: "WENZ-day", exampleSentence: "Wednesday is in the middle of the week.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Thursday", definition: "The fourth day of the week", translation: "", partOfSpeech: "noun", pronunciation: "THURZ-day", exampleSentence: "Thursday is almost Friday.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Friday", definition: "The fifth day of the week", translation: "", partOfSpeech: "noun", pronunciation: "FRY-day", exampleSentence: "Friday is my favorite day.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Saturday", definition: "The sixth day of the week", translation: "", partOfSpeech: "noun", pronunciation: "SAT-er-day", exampleSentence: "I go shopping on Saturday.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Sunday", definition: "The seventh day of the week", translation: "", partOfSpeech: "noun", pronunciation: "SUN-day", exampleSentence: "Sunday is a rest day.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Today", definition: "This current day", translation: "", partOfSpeech: "noun", pronunciation: "tuh-DAY", exampleSentence: "Today is Monday.", exampleTranslation: "", synonyms: "This day", antonyms: "Yesterday", difficulty: "EASY", languageCode: "en" },
      { word: "Tomorrow", definition: "The day after today", translation: "", partOfSpeech: "noun", pronunciation: "tuh-MOR-oh", exampleSentence: "Tomorrow is my birthday.", exampleTranslation: "", synonyms: "Next day", antonyms: "Yesterday", difficulty: "EASY", languageCode: "en" },
      { word: "Yesterday", definition: "The day before today", translation: "", partOfSpeech: "noun", pronunciation: "YES-ter-day", exampleSentence: "Yesterday was Sunday.", exampleTranslation: "", synonyms: "Last day", antonyms: "Tomorrow", difficulty: "EASY", languageCode: "en" },
      { word: "Morning", definition: "The early part of the day", translation: "", partOfSpeech: "noun", pronunciation: "MOR-ning", exampleSentence: "I wake up in the morning.", exampleTranslation: "", synonyms: "AM", antonyms: "Evening", difficulty: "EASY", languageCode: "en" },
      { word: "Afternoon", definition: "The middle part of the day", translation: "", partOfSpeech: "noun", pronunciation: "AF-ter-noon", exampleSentence: "Let's meet in the afternoon.", exampleTranslation: "", synonyms: "PM", antonyms: "Morning", difficulty: "EASY", languageCode: "en" },
      { word: "Evening", definition: "The late part of the day", translation: "", partOfSpeech: "noun", pronunciation: "EEV-ning", exampleSentence: "I study in the evening.", exampleTranslation: "", synonyms: "Night", antonyms: "Morning", difficulty: "EASY", languageCode: "en" },
      { word: "Night", definition: "The dark part of the day", translation: "", partOfSpeech: "noun", pronunciation: "nyte", exampleSentence: "Good night!", exampleTranslation: "", synonyms: "Evening", antonyms: "Day", difficulty: "EASY", languageCode: "en" },
      { word: "Day", definition: "24-hour period of light", translation: "", partOfSpeech: "noun", pronunciation: "day", exampleSentence: "One day has 24 hours.", exampleTranslation: "", synonyms: "Daytime", antonyms: "Night", difficulty: "EASY", languageCode: "en" },
      { word: "Week", definition: "Seven days", translation: "", partOfSpeech: "noun", pronunciation: "week", exampleSentence: "There are seven days in a week.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Month", definition: "A period of about 30 days", translation: "", partOfSpeech: "noun", pronunciation: "munth", exampleSentence: "This month has 31 days.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Year", definition: "A period of 12 months", translation: "", partOfSpeech: "noun", pronunciation: "yeer", exampleSentence: "This year is 2026.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "What time is it?", definition: "A question asking for the current time", translation: "", partOfSpeech: "phrase", pronunciation: "wot tym iz it", exampleSentence: "What time is it now?", exampleTranslation: "", synonyms: "What's the time?", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "It is", definition: "Used to state the time", translation: "", partOfSpeech: "phrase", pronunciation: "it iz", exampleSentence: "It is three o'clock.", exampleTranslation: "", synonyms: "It's", antonyms: "", difficulty: "EASY", languageCode: "en" },
    ]
  },
  {
    title: "Family & Friends",
    description: "Words related to family members and friends",
    level: "A1",
    difficulty: "BEGINNER",
    order: 3,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Family", definition: "A group of people related by blood or marriage", translation: "", partOfSpeech: "noun", pronunciation: "FAM-uh-lee", exampleSentence: "My family is big.", exampleTranslation: "", synonyms: "Relatives", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Father", definition: "A man who has a child", translation: "", partOfSpeech: "noun", pronunciation: "FAH-ther", exampleSentence: "My father is a doctor.", exampleTranslation: "", synonyms: "Dad, Daddy", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Mother", definition: "A woman who has a child", translation: "", partOfSpeech: "noun", pronunciation: "MUH-ther", exampleSentence: "My mother is a teacher.", exampleTranslation: "", synonyms: "Mom, Mommy", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Parent", definition: "A father or mother", translation: "", partOfSpeech: "noun", pronunciation: "PAIR-ent", exampleSentence: "My parents love me.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Child", definition: "A young human being", translation: "", partOfSpeech: "noun", pronunciation: "chyld", exampleSentence: "The child is playing.", exampleTranslation: "", synonyms: "Kid", antonyms: "Adult", difficulty: "EASY", languageCode: "en" },
      { word: "Son", definition: "A male child", translation: "", partOfSpeech: "noun", pronunciation: "sun", exampleSentence: "They have one son.", exampleTranslation: "", synonyms: "", antonyms: "Daughter", difficulty: "EASY", languageCode: "en" },
      { word: "Daughter", definition: "A female child", translation: "", partOfSpeech: "noun", pronunciation: "DAW-ter", exampleSentence: "Their daughter is five.", exampleTranslation: "", synonyms: "", antonyms: "Son", difficulty: "EASY", languageCode: "en" },
      { word: "Brother", definition: "A boy or man with the same parents", translation: "", partOfSpeech: "noun", pronunciation: "BRUH-ther", exampleSentence: "My brother is tall.", exampleTranslation: "", synonyms: "Sibling", antonyms: "Sister", difficulty: "EASY", languageCode: "en" },
      { word: "Sister", definition: "A girl or woman with the same parents", translation: "", partOfSpeech: "noun", pronunciation: "SIS-ter", exampleSentence: "My sister is a nurse.", exampleTranslation: "", synonyms: "Sibling", antonyms: "Brother", difficulty: "EASY", languageCode: "en" },
      { word: "Husband", definition: "A married man", translation: "", partOfSpeech: "noun", pronunciation: "HUZ-band", exampleSentence: "Her husband is a chef.", exampleTranslation: "", synonyms: "", antonyms: "Wife", difficulty: "EASY", languageCode: "en" },
      { word: "Wife", definition: "A married woman", translation: "", partOfSpeech: "noun", pronunciation: "wye", exampleSentence: "His wife is a lawyer.", exampleTranslation: "", synonyms: "", antonyms: "Husband", difficulty: "EASY", languageCode: "en" },
      { word: "Friend", definition: "A person you like and trust", translation: "", partOfSpeech: "noun", pronunciation: "frend", exampleSentence: "She is my best friend.", exampleTranslation: "", synonyms: "Buddy, Pal", antonyms: "Enemy", difficulty: "EASY", languageCode: "en" },
      { word: "Grandfather", definition: "The father of your parent", translation: "", partOfSpeech: "noun", pronunciation: "GRAN-fah-ther", exampleSentence: "My grandfather is 80.", exampleTranslation: "", synonyms: "Grandpa", antonyms: "Grandmother", difficulty: "EASY", languageCode: "en" },
      { word: "Grandmother", definition: "The mother of your parent", translation: "", partOfSpeech: "noun", pronunciation: "GRAN-muh-ther", exampleSentence: "My grandmother bakes cookies.", exampleTranslation: "", synonyms: "Grandma", antonyms: "Grandfather", difficulty: "EASY", languageCode: "en" },
      { word: "Baby", definition: "A very young child", translation: "", partOfSpeech: "noun", pronunciation: "BAY-bee", exampleSentence: "The baby is sleeping.", exampleTranslation: "", synonyms: "Infant", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Boy", definition: "A male child or young man", translation: "", partOfSpeech: "noun", pronunciation: "boy", exampleSentence: "The boy is running.", exampleTranslation: "", synonyms: "", antonyms: "Girl", difficulty: "EASY", languageCode: "en" },
      { word: "Girl", definition: "A female child or young woman", translation: "", partOfSpeech: "noun", pronunciation: "gerl", exampleSentence: "The girl is reading.", exampleTranslation: "", synonyms: "", antonyms: "Boy", difficulty: "EASY", languageCode: "en" },
      { word: "Man", definition: "An adult male human", translation: "", partOfSpeech: "noun", pronunciation: "man", exampleSentence: "The man is tall.", exampleTranslation: "", synonyms: "Guy", antonyms: "Woman", difficulty: "EASY", languageCode: "en" },
      { word: "Woman", definition: "An adult female human", translation: "", partOfSpeech: "noun", pronunciation: "WOO-man", exampleSentence: "The woman is smart.", exampleTranslation: "", synonyms: "Lady", antonyms: "Man", difficulty: "EASY", languageCode: "en" },
      { word: "People", definition: "Human beings in general", translation: "", partOfSpeech: "noun", pronunciation: "PEE-pul", exampleSentence: "Many people live here.", exampleTranslation: "", synonyms: "Folks", antonyms: "", difficulty: "EASY", languageCode: "en" },
    ]
  },
  {
    title: "Body Parts",
    description: "Words for parts of the human body",
    level: "A1",
    difficulty: "BEGINNER",
    order: 4,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Head", definition: "The upper part of the body with the brain", translation: "", partOfSpeech: "noun", pronunciation: "hed", exampleSentence: "My head hurts.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Hair", definition: "The strands growing on the head", translation: "", partOfSpeech: "noun", pronunciation: "hair", exampleSentence: "She has long hair.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Face", definition: "The front part of the head", translation: "", partOfSpeech: "noun", pronunciation: "fays", exampleSentence: "Wash your face.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Eye", definition: "The organ used for seeing", translation: "", partOfSpeech: "noun", pronunciation: "eye", exampleSentence: "She has blue eyes.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Ear", definition: "The organ used for hearing", translation: "", partOfSpeech: "noun", pronunciation: "eer", exampleSentence: "My ears are cold.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Nose", definition: "The organ used for smelling", translation: "", partOfSpeech: "noun", pronunciation: "nohz", exampleSentence: "His nose is big.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Mouth", definition: "The opening used for eating and speaking", translation: "", partOfSpeech: "noun", pronunciation: "mowth", exampleSentence: "Open your mouth.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Tooth", definition: "The hard white objects in the mouth", translation: "", partOfSpeech: "noun", pronunciation: "tooth", exampleSentence: "Brush your teeth.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Tongue", definition: "The organ used for tasting and speaking", translation: "", partOfSpeech: "noun", pronunciation: "tung", exampleSentence: "Don't bite your tongue.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Hand", definition: "The body part at the end of the arm", translation: "", partOfSpeech: "noun", pronunciation: "hand", exampleSentence: "Raise your hand.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Arm", definition: "The body part from shoulder to hand", translation: "", partOfSpeech: "noun", pronunciation: "arm", exampleSentence: "My arms are strong.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Leg", definition: "The body part used for walking", translation: "", partOfSpeech: "noun", pronunciation: "leg", exampleSentence: "My legs are tired.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Foot", definition: "The body part at the end of the leg", translation: "", partOfSpeech: "noun", pronunciation: "foot", exampleSentence: "My feet are cold.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Stomach", definition: "The body part where food is digested", translation: "", partOfSpeech: "noun", pronunciation: "STUM-ak", exampleSentence: "My stomach hurts.", exampleTranslation: "", synonyms: "Belly", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Heart", definition: "The organ that pumps blood", translation: "", partOfSpeech: "noun", pronunciation: "hart", exampleSentence: "My heart is beating fast.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Back", definition: "The rear part of the body", translation: "", partOfSpeech: "noun", pronunciation: "bak", exampleSentence: "My back is sore.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Skin", definition: "The outer covering of the body", translation: "", partOfSpeech: "noun", pronunciation: "skin", exampleSentence: "She has fair skin.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Finger", definition: "One of the parts on the hand", translation: "", partOfSpeech: "noun", pronunciation: "FING-ger", exampleSentence: "I have ten fingers.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Toe", definition: "One of the parts on the foot", translation: "", partOfSpeech: "noun", pronunciation: "toh", exampleSentence: "He stubbed his toe.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
    ]
  },
  {
    title: "Colors",
    description: "Basic colors and color-related words",
    level: "A1",
    difficulty: "BEGINNER",
    order: 5,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Red", definition: "The color of blood or fire", translation: "", partOfSpeech: "adjective", pronunciation: "red", exampleSentence: "The apple is red.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Blue", definition: "The color of the sky or ocean", translation: "", partOfSpeech: "adjective", pronunciation: "bloo", exampleSentence: "The sky is blue.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Green", definition: "The color of grass or leaves", translation: "", partOfSpeech: "adjective", pronunciation: "green", exampleSentence: "The grass is green.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Yellow", definition: "The color of the sun or lemon", translation: "", partOfSpeech: "adjective", pronunciation: "YEL-oh", exampleSentence: "The sun is yellow.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Black", definition: "The darkest color", translation: "", partOfSpeech: "adjective", pronunciation: "blak", exampleSentence: "He has black hair.", exampleTranslation: "", synonyms: "", antonyms: "White", difficulty: "EASY", languageCode: "en" },
      { word: "White", definition: "The lightest color", translation: "", partOfSpeech: "adjective", pronunciation: "hwite", exampleSentence: "Snow is white.", exampleTranslation: "", synonyms: "", antonyms: "Black", difficulty: "EASY", languageCode: "en" },
      { word: "Orange", definition: "The color of an orange fruit", translation: "", partOfSpeech: "adjective", pronunciation: "OR-inj", exampleSentence: "The sunset is orange.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Purple", definition: "The color between red and blue", translation: "", partOfSpeech: "adjective", pronunciation: "PUR-pul", exampleSentence: "She likes purple.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Pink", definition: "A light red color", translation: "", partOfSpeech: "adjective", pronunciation: "pink", exampleSentence: "The flowers are pink.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Brown", definition: "The color of earth or wood", translation: "", partOfSpeech: "adjective", pronunciation: "brown", exampleSentence: "The table is brown.", exampleTranslation: "", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Gray", definition: "The color between black and white", translation: "", partOfSpeech: "adjective", pronunciation: "gray", exampleSentence: "The sky is gray.", exampleTranslation: "", synonyms: "Grey", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Color", definition: "The property of reflecting light", translation: "", partOfSpeech: "noun", pronunciation: "KUL-er", exampleSentence: "What color is your car?", exampleTranslation: "", synonyms: "Colour", antonyms: "", difficulty: "EASY", languageCode: "en" },
      { word: "Light", definition: "Bright or not dark", translation: "", partOfSpeech: "adjective", pronunciation: "lite", exampleSentence: "The room is light.", exampleTranslation: "", synonyms: "Bright", antonyms: "Dark", difficulty: "EASY", languageCode: "en" },
      { word: "Dark", definition: "With little or no light", translation: "", partOfSpeech: "adjective", pronunciation: "dark", exampleSentence: "It is dark outside.", exampleTranslation: "", synonyms: "", antonyms: "Light", difficulty: "EASY", languageCode: "en" },
    ]
  },
];
