export interface VocabWord {
  word: string;
  definition: string;
  partOfSpeech: string;
  pronunciation: string;
  exampleSentence: string;
  synonyms?: string;
  antonyms?: string;
}

export interface VocabSet {
  title: string;
  description: string;
  level: string;
  difficulty: string;
  order: number;
  xpReward: number;
  gemReward: number;
  words: VocabWord[];
}

export const englishC2Data: VocabSet[] = [
  {
    title: "Near-Native Sophisticated Vocabulary",
    description: "Complex vocabulary for nuanced expression and mastery-level communication",
    level: "C2",
    difficulty: "ADVANCED",
    order: 1,
    xpReward: 30,
    gemReward: 8,
    words: [
       { word: "Ubiquitous", definition: "Present, appearing, or found everywhere", partOfSpeech: "adjective", pronunciation: "yoo-BIK-wi-tus", exampleSentence: "Smartphones have become ubiquitous in modern society.", synonyms: "Omnipresent, pervasive", antonyms: "Rare, scarce" },
       { word: "Ephemeral", definition: "Lasting for a very short time", partOfSpeech: "adjective", pronunciation: "i-FEM-er-ul", exampleSentence: "The ephemeral beauty of cherry blossoms.", synonyms: "Fleeting, transient", antonyms: "Permanent, lasting" },
       { word: "Surreptitious", definition: "Kept secret because it would not be approved of", partOfSpeech: "adjective", pronunciation: "sur-up-TISH-us", exampleSentence: "She cast a surreptitious glance at his phone.", synonyms: "Secret, clandestine", antonyms: "Open, overt" },
       { word: "Cacophony", definition: "A harsh, discordant mixture of sounds", partOfSpeech: "noun", pronunciation: "kuh-KOF-uh-nee", exampleSentence: "The cacophony of car horns filled the street.", synonyms: "Dissonance, clamor", antonyms: "Harmony, melody" },
       { word: "Pernicious", definition: "Having a harmful effect in a gradual or subtle way", partOfSpeech: "adjective", pronunciation: "per-NISH-us", exampleSentence: "The pernicious effects of misinformation.", synonyms: "Harmful, destructive", antonyms: "Beneficial, harmless" },
       { word: "Equivocal", definition: "Open to more than one interpretation", partOfSpeech: "adjective", pronunciation: "i-KWIV-uh-kul", exampleSentence: "His equivocal response left us uncertain.", synonyms: "Ambiguous, vague", antonyms: "Clear, unambiguous" },
       { word: "Erudite", definition: "Having or showing great knowledge or learning", partOfSpeech: "adjective", pronunciation: "ER-yoo-dyt", exampleSentence: "The erudite professor published extensively.", synonyms: "Learned, scholarly", antonyms: "Ignorant, uneducated" },
       { word: "Laconic", definition: "Using very few words", partOfSpeech: "adjective", pronunciation: "luh-KON-ik", exampleSentence: "His laconic reply suggested disinterest.", synonyms: "Brief, concise", antonyms: "Verbose, wordy" },
       { word: "Obfuscate", definition: "To make obscure, unclear, or unintelligible", partOfSpeech: "verb", pronunciation: "OB-fuh-skayt", exampleSentence: "The politician tried to obfuscate the truth.", synonyms: "Obscure, confuse", antonyms: "Clarify, elucidate" },
       { word: "Perspicacious", definition: "Having a ready insight into and understanding of things", partOfSpeech: "adjective", pronunciation: "per-spi-KAY-shus", exampleSentence: "The perspicacious analyst predicted the crash.", synonyms: "Perceptive, astute", antonyms: "Obtuse, unperceptive" },
       { word: "Ostentatious", definition: "Characterized by vulgar or pretentious display", partOfSpeech: "adjective", pronunciation: "os-ten-TAY-shus", exampleSentence: "His ostentatious lifestyle attracted criticism.", synonyms: "Showy, pretentious", antonyms: "Modest, unassuming" },
       { word: "Capricious", definition: "Given to sudden and unaccountable changes of mood", partOfSpeech: "adjective", pronunciation: "kuh-PRISH-us", exampleSentence: "The capricious weather made planning difficult.", synonyms: "Unpredictable, fickle", antonyms: "Stable, consistent" },
       { word: "Sagacious", definition: "Having or showing keen mental discernment", partOfSpeech: "adjective", pronunciation: "suh-GAY-shus", exampleSentence: "The sagacious leader made beneficial decisions.", synonyms: "Wise, judicious", antonyms: "Foolish, unwise" },
       { word: "Magnanimous", definition: "Generous or forgiving, especially toward a rival", partOfSpeech: "adjective", pronunciation: "mag-NAN-i-mus", exampleSentence: "She was magnanimous in victory.", synonyms: "Generous, noble", antonyms: "Petty, mean" },
       { word: "Sycophant", definition: "A person who acts obsequiously to gain advantage", partOfSpeech: "noun", pronunciation: "SIK-uh-fant", exampleSentence: "The boss was surrounded by sycophants.", synonyms: "Flatterer, toady", antonyms: "" },
       { word: "Didactic", definition: "Intended to teach, particularly with moral instruction", partOfSpeech: "adjective", pronunciation: "dy-DAK-tik", exampleSentence: "The novel's didactic tone alienated readers.", synonyms: "Instructive, educational", antonyms: "Non-instructive" },
       { word: "Perfunctory", definition: "Carried out with minimum effort or reflection", partOfSpeech: "adjective", pronunciation: "per-FUNGK-tuh-ree", exampleSentence: "He gave a perfunctory nod and continued.", synonyms: "Superficial, cursory", antonyms: "Thorough, diligent" },
       { word: "Propitious", definition: "Giving or indicating a good chance of success", partOfSpeech: "adjective", pronunciation: "pruh-PISH-us", exampleSentence: "The weather was propitious for the concert.", synonyms: "Favorable, auspicious", antonyms: "Unfavorable, adverse" },
       { word: "Auspicious", definition: "Conducive to success; favorable", partOfSpeech: "adjective", pronunciation: "aw-SPISH-us", exampleSentence: "The meeting started under auspicious circumstances.", synonyms: "Promising, favorable", antonyms: "Inauspicious, ominous" },
       { word: "Insidious", definition: "Proceeding in a gradual way with harmful effects", partOfSpeech: "adjective", pronunciation: "in-SID-ee-us", exampleSentence: "The insidious spread of disease went unnoticed.", synonyms: "Stealthy, treacherous", antonyms: "Overt, obvious" },
       { word: "Querulous", definition: "Complaining in a petulant or whining manner", partOfSpeech: "adjective", pronunciation: "KWER-yoo-lus", exampleSentence: "The querulous customer demanded to speak to the manager.", synonyms: "Complaining, whining", antonyms: "Cheerful, content" },
       { word: "Sanguine", definition: "Optimistic or positive, especially in a bad situation", partOfSpeech: "adjective", pronunciation: "SANG-gwin", exampleSentence: "She remained sanguine despite the setbacks.", synonyms: "Optimistic, hopeful", antonyms: "Pessimistic, gloomy" },
       { word: "Taciturn", definition: "Reserved or uncommunicative in speech", partOfSpeech: "adjective", pronunciation: "TAS-i-turn", exampleSentence: "The taciturn old man rarely spoke.", synonyms: "Silent, uncommunicative", antonyms: "Talkative, loquacious" },
       { word: "Vicissitude", definition: "A natural change or variation in circumstances", partOfSpeech: "noun", pronunciation: "vi-SIS-i-tood", exampleSentence: "They remained friends through all life's vicissitudes.", synonyms: "Changes, fluctuations", antonyms: "" },
       { word: "Wanton", definition: "Deliberate and unprovoked; undisciplined", partOfSpeech: "adjective", pronunciation: "WON-tun", exampleSentence: "The wanton destruction shocked the community.", synonyms: "Reckless, unrestrained", antonyms: "Controlled, restrained" },
       { word: "Abnegation", definition: "The action of renouncing or rejecting something", partOfSpeech: "noun", pronunciation: "ab-ni-GAY-shun", exampleSentence: "His abnegation of worldly pleasures impressed everyone.", synonyms: "Renunciation, self-denial", antonyms: "Indulgence, acceptance" },
       { word: "Bellicose", definition: "Demonstrating aggression and willingness to fight", partOfSpeech: "adjective", pronunciation: "BEL-i-kose", exampleSentence: "The bellicose nation threatened its neighbors.", synonyms: "Aggressive, warlike", antonyms: "Peaceful, pacifist" },
       { word: "Circumlocution", definition: "The use of many words where fewer would do", partOfSpeech: "noun", pronunciation: "ser-kum-lo-KYOO-shun", exampleSentence: "His circumlocution annoyed the audience.", synonyms: "Wordiness, periphrasis", antonyms: "Conciseness, brevity" },
       { word: "Ebullient", definition: "Cheerful and full of energy", partOfSpeech: "adjective", pronunciation: "i-BUL-yent", exampleSentence: "The ebullient child filled the room with laughter.", synonyms: "Exuberant, vivacious", antonyms: "Lethargic, depressed" },
       { word: "Fastidious", definition: "Very attentive to detail; very careful", partOfSpeech: "adjective", pronunciation: "fa-STID-ee-us", exampleSentence: "The fastidious editor caught every error.", synonyms: "Meticulous, punctilious", antonyms: "Sloppy, careless" },
       { word: "Garrulous", definition: "Excessively talkative, especially on trivial matters", partOfSpeech: "adjective", pronunciation: "GAR-yoo-lus", exampleSentence: "The garrulous taxi driver talked the entire journey.", synonyms: "Loquacious, talkative", antonyms: "Taciturn, quiet" },
       { word: "Harebrained", definition: "Foolish; impractical", partOfSpeech: "adjective", pronunciation: "HAIR-braynd", exampleSentence: "It was a harebrained scheme from the beginning.", synonyms: "Foolish, silly", antonyms: "Sensible, practical" },
       { word: "Idiosyncrasy", definition: "A mode of behavior peculiar to an individual", partOfSpeech: "noun", pronunciation: "id-ee-oh-SING-kruh-see", exampleSentence: "His humming is just one of his idiosyncrasies.", synonyms: "Quirk, peculiarity", antonyms: "" },
       { word: "Juxtapose", definition: "Place close together for contrasting effect", partOfSpeech: "verb", pronunciation: "jux-tuh-POZ", exampleSentence: "The exhibition juxtaposes modern and classical art.", synonyms: "Contrast, compare", antonyms: "" },
       { word: "Loquacious", definition: "Tending to talk a great deal", partOfSpeech: "adjective", pronunciation: "loh-KWAY-shus", exampleSentence: "The loquacious host kept guests entertained.", synonyms: "Talkative, garrulous", antonyms: "Taciturn, quiet" },
       { word: "Mellifluous", definition: "Sweet or musical; pleasant to hear", partOfSpeech: "adjective", pronunciation: "meh-LIF-loo-us", exampleSentence: "The singer's mellifluous voice captivated the audience.", synonyms: "Melodious, dulcet", antonyms: "Harsh, discordant" },
       { word: "Nefarious", definition: "Wicked or criminal", partOfSpeech: "adjective", pronunciation: "ni-FAIR-ee-us", exampleSentence: "The nefarious plot was discovered in time.", synonyms: "Wicked, villainous", antonyms: "Virtuous, noble" },
       { word: "Obsequious", definition: "Obedient or attentive to an excessive degree", partOfSpeech: "adjective", pronunciation: "ob-SEE-kwee-us", exampleSentence: "The obsequious waiter hovered around the VIP table.", synonyms: "Servile, sycophantic", antonyms: "Assertive, independent" },
       { word: "Pinnacle", definition: "The most successful point; the culmination", partOfSpeech: "noun", pronunciation: "PIN-uh-kul", exampleSentence: "She reached the pinnacle of her career at forty.", synonyms: "Apex, zenith", antonyms: "Nadir, bottom" },
       { word: "Quintessential", definition: "Representing the most perfect or typical example", partOfSpeech: "adjective", pronunciation: "kwin-tuh-SEN-shul", exampleSentence: "This restaurant offers the quintessential Italian experience.", synonyms: "Classic, typical", antonyms: "Atypical, unrepresentative" },
       { word: "Rhetoric", definition: "The art of effective or persuasive speaking", partOfSpeech: "noun", pronunciation: "RET-uh-rik", exampleSentence: "His rhetoric inspired the nation during difficult times.", synonyms: "Oratory, eloquence", antonyms: "" },
       { word: "Sartorial", definition: "Relating to tailoring or clothing", partOfSpeech: "adjective", pronunciation: "sar-TOR-ee-ul", exampleSentence: "His sartorial elegance was noted at every event.", synonyms: "Sartorial, clothing-related", antonyms: "" },
       { word: "Trenchant", definition: "Vigorous or incisive in expression or style", partOfSpeech: "adjective", pronunciation: "TREN-chunt", exampleSentence: "Her trenchant criticism left the committee speechless.", synonyms: "Sharp, incisive", antonyms: "Dull, bland" },
       { word: "Unctuous", definition: "Excessively or ingratiatingly flattering", partOfSpeech: "adjective", pronunciation: "UNGK-choo-us", exampleSentence: "The unctuous salesman made everyone uncomfortable.", synonyms: "Oily, smarmy", antonyms: "Sincere, genuine" },
       { word: "Vitriolic", definition: "Filled with bitter criticism or malice", partOfSpeech: "adjective", pronunciation: "vi-tree-OL-ik", exampleSentence: "The vitriolic review destroyed the filmmaker's reputation.", synonyms: "Bitter, caustic", antonyms: "Praising, complimentary" },
       { word: "Weltschmerz", definition: "A feeling of melancholy and world-weariness", partOfSpeech: "noun", pronunciation: "VELT-shmerts", exampleSentence: "His poetry reflects the Weltschmerz of his generation.", synonyms: "Melancholy, world-weariness", antonyms: "" },
       { word: "Zealous", definition: "Showing passionate and enthusiastic commitment", partOfSpeech: "adjective", pronunciation: "ZEL-us", exampleSentence: "The zealous supporter camped outside for days.", synonyms: "Passionate, fervent", antonyms: "Apathetic, indifferent" },
       { word: "Panacea", definition: "A solution or remedy for all difficulties", partOfSpeech: "noun", pronunciation: "pan-uh-SEE-uh", exampleSentence: "Technology is not a panacea for all educational problems.", synonyms: "Cure-all, universal remedy", antonyms: "" },
       { word: "Sycophancy", definition: "The action of behaving sycophantically", partOfSpeech: "noun", pronunciation: "SIK-uh-fan-see", exampleSentence: "Sycophancy to authority was common in the regime.", synonyms: "Flattery, obsequiousness", antonyms: "" },
       { word: "Grandiloquent", definition: "Pompous or extravagant in language", partOfSpeech: "adjective", pronunciation: "gran-DIL-uh-kwent", exampleSentence: "The politician's grandiloquent speech impressed few.", synonyms: "Bombastic, pompous", antonyms: "Humble, modest" },
       { word: "Pulchritude", definition: "Beauty", partOfSpeech: "noun", pronunciation: "PUL-kri-tood", exampleSentence: "Physical pulchritude is not everything.", synonyms: "Beauty, attractiveness", antonyms: "Ugliness" },
       { word: "Pernickety", definition: "Overly concerned with small details", partOfSpeech: "adjective", pronunciation: "per-NIK-i-tee", exampleSentence: "The pernickety editor corrected every comma.", synonyms: "Fussy, pedantic", antonyms: "Easygoing, lax" },
       { word: "Glib", definition: "Fluent but insincere and shallow", partOfSpeech: "adjective", pronunciation: "glib", exampleSentence: "His glib answers impressed no one.", synonyms: "Superficial, slick", antonyms: "Sincere, thoughtful" },
       { word: "Prolix", definition: "Using or containing too many words", partOfSpeech: "adjective", pronunciation: "PROH-liks", exampleSentence: "His prolix writing style deterred many readers.", synonyms: "Wordy, verbose", antonyms: "Concise, brief" },
       { word: "Obfuscation", definition: "The action of making something obscure or unclear", partOfSpeech: "noun", pronunciation: "ob-fus-KAY-shun", exampleSentence: "The obfuscation of facts was deliberate.", synonyms: "Confusion, obscuration", antonyms: "Clarification" },
       { word: "Sesquipedalian", definition: "Characterized by long words", partOfSpeech: "adjective", pronunciation: "ses-kwi-pe-DAYL-yun", exampleSentence: "His sesquipedalian vocabulary impressed the academics.", synonyms: "Long-winded, verbose", antonyms: "Concise, brief" },
       { word: "Bombastic", definition: "High-sounding but with little meaning", partOfSpeech: "adjective", pronunciation: "bom-BAS-tik", exampleSentence: "The bombastic speech was full of empty promises.", synonyms: "Pompous, grandiloquent", antonyms: "Humble, modest" },
       { word: "Turgid", definition: "Swollen or distended; pompous in style", partOfSpeech: "adjective", pronunciation: "TER-jid", exampleSentence: "The turgid prose was difficult to read.", synonyms: "Pompous, bloated", antonyms: "Simple, clear" },
       { word: "Mendacious", definition: "Not telling the truth; lying", partOfSpeech: "adjective", pronunciation: "men-DAY-shus", exampleSentence: "The mendacious witness was caught in lies.", synonyms: "Dishonest, deceitful", antonyms: "Truthful, honest" },
       { word: "Veracity", definition: "Truthfulness", partOfSpeech: "noun", pronunciation: "vuh-RAS-i-tee", exampleSentence: "The veracity of his statement was questioned.", synonyms: "Truthfulness, honesty", antonyms: "Dishonesty, falsehood" },
       { word: "Pusillanimous", definition: "Showing a lack of courage or resolution", partOfSpeech: "adjective", pronunciation: "pyoo-si-LAN-i-mus", exampleSentence: "The pusillanimous leader fled at the first sign of trouble.", synonyms: "Cowardly, timid", antonyms: "Brave, courageous" },
       { word: "Quixotic", definition: "Exceedingly idealistic; unrealistic", partOfSpeech: "adjective", pronunciation: "kwik-SOT-ik", exampleSentence: "His quixotic quest for perfection was admirable but futile.", synonyms: "Idealistic, unrealistic", antonyms: "Realistic, pragmatic" },
       { word: "Rapacious", definition: "Aggressively greedy or grasping", partOfSpeech: "adjective", pronunciation: "ruh-PAY-shus", exampleSentence: "The rapacious corporation exploited its workers.", synonyms: "Greedy, avaricious", antonyms: "Generous, giving" },
       { word: "Splenetic", definition: "Bad-tempered; spiteful", partOfSpeech: "adjective", pronunciation: "SPLEN-et-ik", exampleSentence: "His splenetic remarks alienated his colleagues.", synonyms: "Irritable, peevish", antonyms: "Good-natured, pleasant" },
       { word: "Truculent", definition: "Eager or quick to argue or fight", partOfSpeech: "adjective", pronunciation: "TRUK-yoo-lunt", exampleSentence: "The truculent teenager constantly challenged authority.", synonyms: "Aggressive, belligerent", antonyms: "Peaceful, gentle" },
       { word: "Uxorious", definition: "Having or showing an excessive or submissive fondness for one's wife", partOfSpeech: "adjective", pronunciation: "uk-SOR-ee-us", exampleSentence: "His uxorious behavior amused his friends.", synonyms: "Dotting, devoted", antonyms: "" },
       { word: "Vicarious", definition: "Experienced in the imagination through another", partOfSpeech: "adjective", pronunciation: "vi-KAIR-ee-us", exampleSentence: "She felt vicarious pride in her son's achievements.", synonyms: "Secondhand, empathetic", antonyms: "" },
       { word: "Waggish", definition: "Characterized by playful humor", partOfSpeech: "adjective", pronunciation: "WAG-ish", exampleSentence: "His waggish comments lightened the mood.", synonyms: "Witty, humorous", antonyms: "Serious, dour" },
       { word: "Xenophile", definition: "A person who is attracted to foreign peoples or cultures", partOfSpeech: "noun", pronunciation: "ZEN-oh-fyl", exampleSentence: "As a xenophile, she loved traveling to new countries.", synonyms: "Cosmopolitan", antonyms: "Xenophobe" },
       { word: "Yeoman", definition: "A person who does loyal and committed service", partOfSpeech: "noun", pronunciation: "YOH-mun", exampleSentence: "The yeoman served the company faithfully for decades.", synonyms: "Loyal servant, stalwart", antonyms: "" },
       { word: "Zeitgeist", definition: "The spirit of the time", partOfSpeech: "noun", pronunciation: "TSYT-gyst", exampleSentence: "The novel captured the zeitgeist of the 1920s.", synonyms: "Spirit, ethos", antonyms: "" },
       { word: "Atavistic", definition: "Relating to atavism; reversion to ancestral type", partOfSpeech: "adjective", pronunciation: "at-uh-VIS-tik", exampleSentence: "His atavistic fears surfaced during the storm.", synonyms: "Primitive, ancestral", antonyms: "" },
       { word: "Borborygmus", definition: "A rumbling noise caused by gas in the intestine", partOfSpeech: "noun", pronunciation: "bor-buh-RIG-mus", exampleSentence: "The embarrassing borborygmus interrupted the silent meeting.", synonyms: "", antonyms: "" },
       { word: "Chatoyant", definition: "Having a changeable luster like a cat's eye", partOfSpeech: "adjective", pronunciation: "sha-TOY-unt", exampleSentence: "The chatoyant silk shimmered in the light.", synonyms: "Iridescent, shimmering", antonyms: "" },
       { word: "Discombobulate", definition: "To confuse or disconcert", partOfSpeech: "verb", pronunciation: "dis-kum-BOB-yoo-layt", exampleSentence: "The complex instructions discombobulated the students.", synonyms: "Confuse, bewilder", antonyms: "Clarify, enlighten" },
       { word: "Effulgent", definition: "Shining brightly; radiant", partOfSpeech: "adjective", pronunciation: "i-FUL-junt", exampleSentence: "The effulgent sun lit up the entire valley.", synonyms: "Brilliant, radiant", antonyms: "Dull, dim" },
       { word: "Floccinaucinihilipilification", definition: "The action of estimating something as worthless", partOfSpeech: "noun", pronunciation: "flok-si-naw-see-ni-hil-i-pil-i-fi-KAY-shun", exampleSentence: "His floccinaucinihilipilification of modern art shocked the gallery owner.", synonyms: "Disdain, contempt", antonyms: "Appreciation, valuation" },
       { word: "Gobbledygook", definition: "Language that is meaningless or hard to understand", partOfSpeech: "noun", pronunciation: "GOB-ul-dee-gook", exampleSentence: "The contract was full of legal gobbledygook.", synonyms: "Jargon, nonsense", antonyms: "Clarity, plain language" },
       { word: "Hippopotomonstrosesquippedaliophobia", definition: "Fear of long words", partOfSpeech: "noun", pronunciation: "hip-oh-poh-toh-mon-stro-ses-kwi-pe-dal-io-PHO-bia", exampleSentence: "Ironically, hippopotomonstrosesquippedaliophobia is itself a long word.", synonyms: "", antonyms: "" }
       ]
  },
  {
    title: "Advanced Literature & Literary Terms",
    description: "Sophisticated vocabulary for literary analysis and criticism",
    level: "C2",
    difficulty: "ADVANCED",
    order: 2,
    xpReward: 30,
    gemReward: 8,
    words: [
       { word: "Allegory", definition: "Story with hidden meaning", partOfSpeech: "noun", pronunciation: "AL-i-gor-ee", exampleSentence: "Literary allegory.", synonyms: "Metaphor, symbol", antonyms: "" },
       { word: "Metaphor", definition: "Implicit comparison", partOfSpeech: "noun", pronunciation: "MET-uh-for", exampleSentence: "Powerful metaphor.", synonyms: "Figure of speech", antonyms: "" },
       { word: "Simile", definition: "Explicit comparison using like/as", partOfSpeech: "noun", pronunciation: "SIM-i-lee", exampleSentence: "Clear simile.", synonyms: "Comparison", antonyms: "" },
       { word: "Personification", definition: "Giving human traits to objects", partOfSpeech: "noun", pronunciation: "per-son-i-fi-KAY-shun", exampleSentence: "Clever personification.", synonyms: "", antonyms: "" },
       { word: "Onomatopoeia", definition: "Words that sound like their meaning", partOfSpeech: "noun", pronunciation: "on-uh-mat-uh-PEE-uh", exampleSentence: "Onomatopoeia examples.", synonyms: "", antonyms: "" },
       { word: "Alliteration", definition: "Repetition of initial sounds", partOfSpeech: "noun", pronunciation: "uh-lit-uh-RAY-shun", exampleSentence: "Alliteration in poetry.", synonyms: "", antonyms: "" },
       { word: "Assonance", definition: "Repetition of vowel sounds", partOfSpeech: "noun", pronunciation: "AS-uh-nuns", exampleSentence: "Assonance creates mood.", synonyms: "", antonyms: "" },
       { word: "Consonance", definition: "Repetition of consonant sounds", partOfSpeech: "noun", pronunciation: "KON-suh-nuns", exampleSentence: "Consonance in verse.", synonyms: "", antonyms: "" },
       { word: "Rhyme", definition: "Corresponding sounds in words", partOfSpeech: "noun", pronunciation: "rym", exampleSentence: "Perfect rhyme.", synonyms: "", antonyms: "" },
       { word: "Meter", definition: "Rhythmic structure in poetry", partOfSpeech: "noun", pronunciation: "MEE-ter", exampleSentence: "Iambic meter.", synonyms: "Rhythm", antonyms: "" },
       { word: "Iambic", definition: "Metrical foot with unstressed-stressed", partOfSpeech: "adjective", pronunciation: "y-AM-bik", exampleSentence: "Iambic pentameter.", synonyms: "", antonyms: "" },
       { word: "Pentameter", definition: "Line with five metrical feet", partOfSpeech: "noun", pronunciation: "pen-TAM-i-ter", exampleSentence: "Shakespeare's pentameter.", synonyms: "", antonyms: "" },
       { word: "Sonnet", definition: "14-line poetic form", partOfSpeech: "noun", pronunciation: "SON-it", exampleSentence: "Shakespearean sonnet.", synonyms: "", antonyms: "" },
       { word: "Epic", definition: "Long heroic narrative poem", partOfSpeech: "noun", pronunciation: "EP-ik", exampleSentence: "Epic poetry.", synonyms: "Saga, odyssey", antonyms: "" },
       { word: "Lyric", definition: "Emotional, song-like poetry", partOfSpeech: "adjective", pronunciation: "LIR-ik", exampleSentence: "Lyric poetry.", synonyms: "Song-like", antonyms: "" },
       { word: "Ballad", definition: "Narrative poem or song", partOfSpeech: "noun", pronunciation: "BAL-ud", exampleSentence: "Folk ballad.", synonyms: "Narrative song", antonyms: "" },
       { word: "Ode", definition: "Poem of praise", partOfSpeech: "noun", pronunciation: "ohd", exampleSentence: "Ode to joy.", synonyms: "Hymn, tribute", antonyms: "" },
       { word: "Elegy", definition: "Poem of mourning", partOfSpeech: "noun", pronunciation: "EL-i-jee", exampleSentence: "Pastoral elegy.", synonyms: "Lament, dirge", antonyms: "" },
       { word: "Satire", definition: "Use of irony to criticize", partOfSpeech: "noun", pronunciation: "SAT-yr", exampleSentence: "Political satire.", synonyms: "Parody, irony", antonyms: "" },
       { word: "Parody", definition: "Imitation for comic effect", partOfSpeech: "noun", pronunciation: "PAR-uh-dee", exampleSentence: "Literary parody.", synonyms: "Spoof, satire", antonyms: "" },
       { word: "Irony", definition: "Contrast between expectation and reality", partOfSpeech: "noun", pronunciation: "Y-ruh-nee", exampleSentence: "Dramatic irony.", synonyms: "Paradox, sarcasm", antonyms: "" },
       { word: "Sarcasm", definition: "Cutting, ironic remark", partOfSpeech: "noun", pronunciation: "SAR-kaz-um", exampleSentence: "Bitter sarcasm.", synonyms: "Irony, ridicule", antonyms: "" },
       { word: "Foreshadowing", definition: "Hint of future events", partOfSpeech: "noun", pronunciation: "for-SHAD-oh-ing", exampleSentence: "Foreshadowing in novels.", synonyms: "Prefiguring", antonyms: "" },
       { word: "Flashback", definition: "Return to earlier time", partOfSpeech: "noun", pronunciation: "FLASH-bak", exampleSentence: "Narrative flashback.", synonyms: "Retrospection", antonyms: "" },
       { word: "Motif", definition: "Recurring thematic element", partOfSpeech: "noun", pronunciation: "moh-TEEF", exampleSentence: "Literary motif.", synonyms: "Theme, pattern", antonyms: "" },
       { word: "Leitmotif", definition: "Recurring musical theme", partOfSpeech: "noun", pronunciation: "LYT-moh-teef", exampleSentence: "Wagnerian leitmotif.", synonyms: "Theme, motif", antonyms: "" },
       { word: "Archetype", definition: "Original pattern or model", partOfSpeech: "noun", pronunciation: "AHR-kuh-typ", exampleSentence: "Jungian archetype.", synonyms: "Prototype, ideal", antonyms: "" },
       { word: "Stereotype", definition: "Oversimplified generalization", partOfSpeech: "noun", pronunciation: "STER-ee-uh-typ", exampleSentence: "Break stereotypes.", synonyms: "Generalization", antonyms: "" },
       { word: "Narrative", definition: "Telling of a story", partOfSpeech: "noun", pronunciation: "NAR-uh-tiv", exampleSentence: "Compelling narrative.", synonyms: "Story, account", antonyms: "" },
       { word: "Denouement", definition: "Final resolution in plot", partOfSpeech: "noun", pronunciation: "day-noo-MAHN", exampleSentence: "Surprising denouement.", synonyms: "Resolution, outcome", antonyms: "" },
       { word: "Climax", definition: "Most intense point", partOfSpeech: "noun", pronunciation: "KLY-maks", exampleSentence: "Story climax.", synonyms: "Peak, culmination", antonyms: "" },
       { word: "Antagonist", definition: "Opponent of the protagonist", partOfSpeech: "noun", pronunciation: "an-TAG-uh-nist", exampleSentence: "Villainous antagonist.", synonyms: "Rival, opponent", antonyms: "Protagonist" },
       { word: "Protagonist", definition: "Main character", partOfSpeech: "noun", pronunciation: "proh-TAG-uh-nist", exampleSentence: "Heroic protagonist.", synonyms: "Hero, lead", antonyms: "Antagonist" },
       { word: "Foil", definition: "Character contrasting another", partOfSpeech: "noun", pronunciation: "foyl", exampleSentence: "Character foil.", synonyms: "Contrast", antonyms: "" },
       { word: "Aside", definition: "Character speaks to audience", partOfSpeech: "noun", pronunciation: "uh-SYD", exampleSentence: "Dramatic aside.", synonyms: "", antonyms: "" },
       { word: "Soliloquy", definition: "Speech to oneself on stage", partOfSpeech: "noun", pronunciation: "suh-LIL-uh-kwee", exampleSentence: "Shakespearean soliloquy.", synonyms: "Monologue", antonyms: "" },
       { word: "Monologue", definition: "Long speech by one person", partOfSpeech: "noun", pronunciation: "MON-uh-log", exampleSentence: "Dramatic monologue.", synonyms: "Soliloquy", antonyms: "Dialogue" },
       { word: "Dialogue", definition: "Conversation between characters", partOfSpeech: "noun", pronunciation: "DY-uh-log", exampleSentence: "Witty dialogue.", synonyms: "Conversation", antonyms: "Monologue" },
       { word: "Genre", definition: "Category of artistic work", partOfSpeech: "noun", pronunciation: "ZHAHN-ruh", exampleSentence: "Literary genre.", synonyms: "Category, type", antonyms: "" },
       { word: "Renaissance", definition: "Revival of art and learning", partOfSpeech: "noun", pronunciation: "REN-uh-sahns", exampleSentence: "Renaissance literature.", synonyms: "Rebirth, revival", antonyms: "" },
       { word: "Gothic", definition: "Medieval style; dark romantic", partOfSpeech: "adjective", pronunciation: "GOTH-ik", exampleSentence: "Gothic novel.", synonyms: "Medieval, dark", antonyms: "" },
       { word: "Romanticism", definition: "Movement emphasizing emotion", partOfSpeech: "noun", pronunciation: "roh-MAN-ti-siz-um", exampleSentence: "Romanticism era.", synonyms: "Romantic movement", antonyms: "" }
       ]
  },
  {
    title: "Advanced Philosophy & Ethics",
    description: "Vocabulary for philosophical discourse and ethical reasoning",
    level: "C2",
    difficulty: "ADVANCED",
    order: 3,
    xpReward: 30,
    gemReward: 8,
    words: [
       { word: "Epistemology", definition: "Study of knowledge and knowing", partOfSpeech: "noun", pronunciation: "i-pis-tuh-MOL-uh-jee", exampleSentence: "Study epistemology.", synonyms: "Knowledge theory", antonyms: "" },
       { word: "Ontology", definition: "Study of being and existence", partOfSpeech: "noun", pronunciation: "on-TOL-uh-jee", exampleSentence: "Ontology.", synonyms: "Existence theory", antonyms: "" },
       { word: "Metaphysics", definition: "Study of fundamental reality", partOfSpeech: "noun", pronunciation: "met-uh-FIZ-iks", exampleSentence: "Metaphysical questions.", synonyms: "Abstract philosophy", antonyms: "" },
       { word: "Axiology", definition: "Study of value and worth", partOfSpeech: "noun", pronunciation: "ak-see-OL-uh-jee", exampleSentence: "Axiology of art.", synonyms: "Value theory", antonyms: "" },
       { word: "Ethics", definition: "Study of moral principles", partOfSpeech: "noun", pronunciation: "ETH-iks", exampleSentence: "Professional ethics.", synonyms: "Morality, morals", antonyms: "" },
       { word: "Deontology", definition: "Duty-based ethics", partOfSpeech: "noun", pronunciation: "dee-on-TOL-uh-jee", exampleSentence: "Deontological ethics.", synonyms: "Duty ethics", antonyms: "" },
       { word: "Consequentialism", definition: "Outcome-based ethics", partOfSpeech: "noun", pronunciation: "kun-see-KWEN-shul-iz-um", exampleSentence: "Consequentialist theory.", synonyms: "Result-based ethics", antonyms: "" },
       { word: "Utilitarianism", definition: "Greatest good for greatest number", partOfSpeech: "noun", pronunciation: "yoo-til-i-TAIR-ee-un-iz-um", exampleSentence: "Utilitarian philosophy.", synonyms: "Greatest happiness", antonyms: "" },
       { word: "Virtue ethics", definition: "Character-based ethics", partOfSpeech: "noun", pronunciation: "VER-choo ETH-iks", exampleSentence: "Virtue ethics approach.", synonyms: "Character ethics", antonyms: "" },
       { word: "Aesthetics", definition: "Study of beauty and taste", partOfSpeech: "noun", pronunciation: "es-THET-iks", exampleSentence: "Philosophy of aesthetics.", synonyms: "Beauty theory", antonyms: "" },
       { word: "Phenomenology", definition: "Study of structures of consciousness", partOfSpeech: "noun", pronunciation: "fi-nom-uh-NOL-uh-jee", exampleSentence: "Phenomenology.", synonyms: "Consciousness study", antonyms: "" },
       { word: "Existentialism", definition: "Focus on individual existence", partOfSpeech: "noun", pronunciation: "eg-zis-TEN-shul-iz-um", exampleSentence: "Existentialist philosophy.", synonyms: "Individualism", antonyms: "" },
       { word: "Nihilism", definition: "Rejection of all religious beliefs", partOfSpeech: "noun", pronunciation: "NY-hil-iz-um", exampleSentence: "Philosophical nihilism.", synonyms: "Rejection of meaning", antonyms: "" },
       { word: "Stoicism", definition: "Endurance of pain without complaint", partOfSpeech: "noun", pronunciation: "STOH-i-siz-um", exampleSentence: "Stoic philosophy.", synonyms: "Endurance, patience", antonyms: "" },
       { word: "Hedonism", definition: "Pursuit of pleasure", partOfSpeech: "noun", pronunciation: "HEED-un-iz-um", exampleSentence: "Ethical hedonism.", synonyms: "Pleasure-seeking", antonyms: "" },
       { word: "Altruism", definition: "Selfless concern for others", partOfSpeech: "noun", pronunciation: "AL-troo-iz-um", exampleSentence: "Act of altruism.", synonyms: "Selflessness", antonyms: "Egoism" },
       { word: "Egoism", definition: "Self-interest as motivation", partOfSpeech: "noun", pronunciation: "EE-goh-iz-um", exampleSentence: "Psychological egoism.", synonyms: "Selfishness", antonyms: "Altruism" },
       { word: "Determinism", definition: "All events are caused", partOfSpeech: "noun", pronunciation: "di-TER-mun-iz-um", exampleSentence: "Hard determinism.", synonyms: "Causality", antonyms: "Free will" },
       { word: "Free will", definition: "Ability to choose freely", partOfSpeech: "noun", pronunciation: "free wil", exampleSentence: "Debate on free will.", synonyms: "Autonomy", antonyms: "Determinism" },
       { word: "Dualism", definition: "Division into two parts", partOfSpeech: "noun", pronunciation: "DOO-ul-iz-um", exampleSentence: "Mind-body dualism.", synonyms: "Division, dichotomy", antonyms: "Monism" },
       { word: "Monism", definition: "All is one substance", partOfSpeech: "noun", pronunciation: "MOH-niz-um", exampleSentence: "Materialist monism.", synonyms: "Unity", antonyms: "Dualism" },
       { word: "Pluralism", definition: "Multiple fundamental types", partOfSpeech: "noun", pronunciation: "PLOOR-ul-iz-um", exampleSentence: "Value pluralism.", synonyms: "Diversity", antonyms: "Monism" },
       { word: "Rationalism", definition: "Knowledge through reason", partOfSpeech: "noun", pronunciation: "RASH-un-ul-iz-um", exampleSentence: "Cartesian rationalism.", synonyms: "Reason-based", antonyms: "Empiricism" },
       { word: "Empiricism", definition: "Knowledge through experience", partOfSpeech: "noun", pronunciation: "em-PIR-i-siz-um", exampleSentence: "British empiricism.", synonyms: "Experience-based", antonyms: "Rationalism" },
       { word: "Skepticism", definition: "Questioning knowledge claims", partOfSpeech: "noun", pronunciation: "SKEP-ti-siz-um", exampleSentence: "Philosophical skepticism.", synonyms: "Doubt, questioning", antonyms: "Dogmatism" },
       { word: "Dogmatism", definition: "Stating opinions strongly", partOfSpeech: "noun", pronunciation: "DOG-muh-tiz-um", exampleSentence: "Religious dogmatism.", synonyms: "Rigid belief", antonyms: "Skepticism" },
       { word: "Pragmatism", definition: "Practical consequences matter", partOfSpeech: "noun", pronunciation: "PRAG-muh-tiz-um", exampleSentence: "Pragmatic philosophy.", synonyms: "Practicality", antonyms: "Idealism" },
       { word: "Idealism", definition: "Reality is mentally constructed", partOfSpeech: "noun", pronunciation: "y-DEE-ul-iz-um", exampleSentence: "German idealism.", synonyms: "Mental reality", antonyms: "Materialism" },
       { word: "Materialism", definition: "Reality is physical matter", partOfSpeech: "noun", pronunciation: "muh-TEER-ee-ul-iz-um", exampleSentence: "Dialectical materialism.", synonyms: "Physical reality", antonyms: "Idealism" },
       { word: "Relativism", definition: "Truth is relative to perspective", partOfSpeech: "noun", pronunciation: "REL-uh-tiv-iz-um", exampleSentence: "Moral relativism.", synonyms: "Perspectivism", antonyms: "Absolutism" },
       { word: "Absolutism", definition: "Universal moral truths exist", partOfSpeech: "noun", pronunciation: "AB-suh-loot-iz-um", exampleSentence: "Moral absolutism.", synonyms: "Universalism", antonyms: "Relativism" },
       { word: "Normative", definition: "Establishing rules or standards", partOfSpeech: "adjective", pronunciation: "NOR-muh-tiv", exampleSentence: "Normative ethics.", synonyms: "Prescriptive", antonyms: "Descriptive" },
       { word: "Descriptive", definition: "Describing without judgment", partOfSpeech: "adjective", pronunciation: "di-SKRIP-tiv", exampleSentence: "Descriptive ethics.", synonyms: "Non-judgmental", antonyms: "Normative" },
       { word: "Subjective", definition: "Based on personal feelings", partOfSpeech: "adjective", pronunciation: "sub-JEK-tiv", exampleSentence: "Subjective experience.", synonyms: "Personal", antonyms: "Objective" },
       { word: "Objective", definition: "Not influenced by personal feelings", partOfSpeech: "adjective", pronunciation: "ob-JEK-tiv", exampleSentence: "Objective truth.", synonyms: "Impartial, factual", antonyms: "Subjective" },
       { word: "A priori", definition: "Independent of experience", partOfSpeech: "adjective", pronunciation: "ah pree-OR-ee", exampleSentence: "A priori knowledge.", synonyms: "Theoretical", antonyms: "A posteriori" },
       { word: "A posteriori", definition: "Dependent on experience", partOfSpeech: "adjective", pronunciation: "ah pos-ter-ee-OR-ee", exampleSentence: "A posteriori reasoning.", synonyms: "Empirical", antonyms: "A priori" },
       { word: "Synthetic", definition: "Adding new information", partOfSpeech: "adjective", pronunciation: "sin-THET-ik", exampleSentence: "Synthetic proposition.", synonyms: "Informative", antonyms: "Analytic" },
       { word: "Analytic", definition: "True by definition alone", partOfSpeech: "adjective", pronunciation: "an-uh-LIT-ik", exampleSentence: "Analytic proposition.", synonyms: "Self-evident", antonyms: "Synthetic" }
       ]
  },
  {
    title: "C2: Advanced Medicine & Pathology",
    description: "Specialized medical terminology for proficient learners",
    level: "C2",
    difficulty: "ADVANCED",
    order: 4,
    xpReward: 30,
    gemReward: 8,
    words: [
       { word: "Pathogenesis", definition: "Development of disease", partOfSpeech: "noun", pronunciation: "path-oh-JEN-eh-sis", exampleSentence: "Study the pathogenesis.", synonyms: "Disease development", antonyms: "" },
       { word: "Etiology", definition: "Cause of disease", partOfSpeech: "noun", pronunciation: "ee-tee-OL-oh-jee", exampleSentence: "Determine the etiology.", synonyms: "Origin, cause", antonyms: "" },
       { word: "Symptomatology", definition: "Study of symptoms", partOfSpeech: "noun", pronunciation: "simp-toh-muh-TOL-oh-jee", exampleSentence: "Symptomatology analysis.", synonyms: "Symptom study", antonyms: "" },
       { word: "Nosology", definition: "Classification of diseases", partOfSpeech: "noun", pronunciation: "noh-SOL-oh-jee", exampleSentence: "Medical nosology.", synonyms: "Disease classification", antonyms: "" },
       { word: "Iatrogenic", definition: "Caused by medical treatment", partOfSpeech: "adjective", pronunciation: "y-uh-tree-OH-jen-ik", exampleSentence: "Iatrogenic complications.", synonyms: "Treatment-caused", antonyms: "" },
       { word: "Idiopathic", definition: "Of unknown cause", partOfSpeech: "adjective", pronunciation: "id-ee-oh-PATH-ik", exampleSentence: "Idiopathic condition.", synonyms: "Spontaneous, unknown", antonyms: "" },
       { word: "Congenital", definition: "Present from birth", partOfSpeech: "adjective", pronunciation: "kon-JEN-i-tal", exampleSentence: "Congenital defect.", synonyms: "Inherited, innate", antonyms: "Acquired" },
       { word: "Acquired", definition: "Developed after birth", partOfSpeech: "adjective", pronunciation: "uh-KWY-erd", exampleSentence: "Acquired condition.", synonyms: "Developed", antonyms: "Congenital" },
       { word: "Acute", definition: "Severe but short-term", partOfSpeech: "adjective", pronunciation: "uh-KYOOT", exampleSentence: "Acute infection.", synonyms: "Severe, sharp", antonyms: "Chronic" },
       { word: "Chronic", definition: "Long-lasting disease", partOfSpeech: "adjective", pronunciation: "KRON-ik", exampleSentence: "Chronic illness.", synonyms: "Persistent, long-term", antonyms: "Acute" },
       { word: "Malignant", definition: "Cancerous, harmful", partOfSpeech: "adjective", pronunciation: "muh-LIG-nunt", exampleSentence: "Malignant tumor.", synonyms: "Cancerous, harmful", antonyms: "Benign" },
       { word: "Benign", definition: "Not harmful or cancerous", partOfSpeech: "adjective", pronunciation: "bi-NYN", exampleSentence: "Benign growth.", synonyms: "Harmless, non-cancerous", antonyms: "Malignant" },
       { word: "Metastasis", definition: "Spread of cancer", partOfSpeech: "noun", pronunciation: "meh-TAS-tuh-sis", exampleSentence: "Cancer metastasis.", synonyms: "Cancer spread", antonyms: "" },
       { word: "Prognosis", definition: "Likely outcome of disease", partOfSpeech: "noun", pronunciation: "prog-NOH-sis", exampleSentence: "Poor prognosis.", synonyms: "Forecast, outlook", antonyms: "" },
       { word: "Diagnosis", definition: "Identification of disease", partOfSpeech: "noun", pronunciation: "dy-ag-NOH-sis", exampleSentence: "Accurate diagnosis.", synonyms: "Identification", antonyms: "" },
       { word: "Differential diagnosis", definition: "Distinguishing similar conditions", partOfSpeech: "noun", pronunciation: "dif-uh-REN-shul dy-ag-NOH-sis", exampleSentence: "Differential diagnosis process.", synonyms: "Distinguishing diagnosis", antonyms: "" },
       { word: "Prophylaxis", definition: "Disease prevention", partOfSpeech: "noun", pronunciation: "prof-i-LAK-sis", exampleSentence: "Antibiotic prophylaxis.", synonyms: "Prevention", antonyms: "" },
       { word: "Therapeutics", definition: "Treatment of disease", partOfSpeech: "noun", pronunciation: "ther-uh-PYOO-tiks", exampleSentence: "Advanced therapeutics.", synonyms: "Treatment, therapy", antonyms: "" },
       { word: "Pathophysiology", definition: "Function of diseased organs", partOfSpeech: "noun", pronunciation: "path-oh-fiz-ee-OL-oh-jee", exampleSentence: "Study pathophysiology.", synonyms: "Disease function", antonyms: "" },
       { word: "Immunopathology", definition: "Immune system diseases", partOfSpeech: "noun", pronunciation: "im-yoo-noh-puh-THOL-oh-jee", exampleSentence: "Immunopathology research.", synonyms: "Immune disease study", antonyms: "" },
       { word: "Neuropathology", definition: "Nervous system diseases", partOfSpeech: "noun", pronunciation: "noor-oh-puh-THOL-oh-jee", exampleSentence: "Neuropathology specialist.", synonyms: "Nerve disease study", antonyms: "" },
       { word: "Psychopathology", definition: "Study of mental disorders", partOfSpeech: "noun", pronunciation: "sy-koh-puh-THOL-oh-jee", exampleSentence: "Psychopathology analysis.", synonyms: "Mental disorder study", antonyms: "" },
       { word: "Epidemiology", definition: "Study of disease spread", partOfSpeech: "noun", pronunciation: "ep-i-dee-mee-OL-oh-jee", exampleSentence: "Epidemiology research.", synonyms: "Disease distribution", antonyms: "" },
       { word: "Pharmacokinetics", definition: "Drug movement in body", partOfSpeech: "noun", pronunciation: "far-muh-koh-ki-NET-iks", exampleSentence: "Pharmacokinetics study.", synonyms: "Drug kinetics", antonyms: "" },
       { word: "Pharmacodynamics", definition: "Drug effects on body", partOfSpeech: "noun", pronunciation: "far-muh-koh-dy-NAM-iks", exampleSentence: "Pharmacodynamics research.", synonyms: "Drug effects", antonyms: "" },
       { word: "Contraindication", definition: "Reason not to use treatment", partOfSpeech: "noun", pronunciation: "kon-truh-in-di-KAY-shun", exampleSentence: "Drug contraindication.", synonyms: "Warning, restriction", antonyms: "" },
       { word: "Idiosyncratic", definition: "Peculiar to the individual", partOfSpeech: "adjective", pronunciation: "id-ee-oh-sin-KRAT-ik", exampleSentence: "Idiosyncratic reaction.", synonyms: "Individual, peculiar", antonyms: "Common, typical" },
       { word: "Anaphylaxis", definition: "Severe allergic reaction", partOfSpeech: "noun", pronunciation: "an-uh-fi-LAK-sis", exampleSentence: "Anaphylactic shock.", synonyms: "Severe allergy", antonyms: "" },
       { word: "Necrosis", definition: "Death of tissue", partOfSpeech: "noun", pronunciation: "neh-KROH-sis", exampleSentence: "Tissue necrosis.", synonyms: "Tissue death", antonyms: "Viability" },
       { word: "Atrophy", definition: "Wasting away of body part", partOfSpeech: "noun", pronunciation: "AT-ruh-fee", exampleSentence: "Muscle atrophy.", synonyms: "Wasting, deterioration", antonyms: "Hypertrophy" },
       { word: "Hypertrophy", definition: "Enlargement of organ", partOfSpeech: "noun", pronunciation: "hy-PER-truh-fee", exampleSentence: "Cardiac hypertrophy.", synonyms: "Enlargement", antonyms: "Atrophy" },
       { word: "Dysplasia", definition: "Abnormal development", partOfSpeech: "noun", pronunciation: "dis-PLAY-zhuh", exampleSentence: "Hip dysplasia.", synonyms: "Abnormal growth", antonyms: "Normal development" },
       { word: "Hyperplasia", definition: "Increase in cell number", partOfSpeech: "noun", pronunciation: "hy-per-PLAY-zhuh", exampleSentence: "Benign hyperplasia.", synonyms: "Cell increase", antonyms: "Hypoplasia" },
       { word: "Neoplasia", definition: "New tissue formation", partOfSpeech: "noun", pronunciation: "nee-oh-PLAY-zhuh", exampleSentence: "Neoplastic growth.", synonyms: "Tumor formation", antonyms: "" },
       { word: "Ischemia", definition: "Restriction of blood supply", partOfSpeech: "noun", pronunciation: "iss-KEE-mee-uh", exampleSentence: "Cardiac ischemia.", synonyms: "Blood restriction", antonyms: "Perfusion" },
       { word: "Hemorrhage", definition: "Heavy bleeding", partOfSpeech: "noun", pronunciation: "HEM-uh-rij", exampleSentence: "Internal hemorrhage.", synonyms: "Bleeding, blood loss", antonyms: "" },
       { word: "Thrombosis", definition: "Blood clot formation", partOfSpeech: "noun", pronunciation: "throm-BOH-sis", exampleSentence: "Deep vein thrombosis.", synonyms: "Clotting", antonyms: "" },
       { word: "Embolism", definition: "Blockage by traveling particle", partOfSpeech: "noun", pronunciation: "EM-boh-liz-um", exampleSentence: "Pulmonary embolism.", synonyms: "Blockage", antonyms: "" },
       { word: "Aneurysm", definition: "Blood vessel bulge", partOfSpeech: "noun", pronunciation: "AN-yoo-riz-um", exampleSentence: "Brain aneurysm.", synonyms: "Vessel bulge", antonyms: "" },
       { word: "Atherosclerosis", definition: "Artery hardening", partOfSpeech: "noun", pronunciation: "ath-uh-roh-skleh-ROH-sis", exampleSentence: "Coronary atherosclerosis.", synonyms: "Artery hardening", antonyms: "" },
       { word: "Fibrosis", definition: "Scar tissue formation", partOfSpeech: "noun", pronunciation: "fy-BROH-sis", exampleSentence: "Liver fibrosis.", synonyms: "Scarring", antonyms: "" },
       { word: "Cirrhosis", definition: "Liver scarring", partOfSpeech: "noun", pronunciation: "si-ROH-sis", exampleSentence: "Alcoholic cirrhosis.", synonyms: "Liver scarring", antonyms: "" },
       { word: "Sepsis", definition: "Body-wide infection", partOfSpeech: "noun", pronunciation: "SEP-sis", exampleSentence: "Septic shock.", synonyms: "Blood infection", antonyms: "" },
       { word: "Bacteremia", definition: "Bacteria in blood", partOfSpeech: "noun", pronunciation: "bak-ter-EE-mee-uh", exampleSentence: "Bacteremia detected.", synonyms: "Blood infection", antonyms: "" },
       { word: "Viremia", definition: "Virus in bloodstream", partOfSpeech: "noun", pronunciation: "vy-REE-mee-uh", exampleSentence: "Viremia phase.", synonyms: "", antonyms: "" },
       { word: "Asymptomatic", definition: "Not showing symptoms", partOfSpeech: "adjective", pronunciation: "ay-simp-tuh-MAT-ik", exampleSentence: "Asymptomatic carrier.", synonyms: "Without symptoms", antonyms: "Symptomatic" },
       { word: "Symptomatic", definition: "Showing symptoms", partOfSpeech: "adjective", pronunciation: "simp-tuh-MAT-ik", exampleSentence: "Symptomatic patient.", synonyms: "Showing signs", antonyms: "Asymptomatic" },
       { word: "Exacerbation", definition: "Worsening of symptoms", partOfSpeech: "noun", pronunciation: "ig-zas-er-BAY-shun", exampleSentence: "Disease exacerbation.", synonyms: "Worsening, aggravation", antonyms: "Improvement" },
       { word: "Remission", definition: "Temporary disappearance", partOfSpeech: "noun", pronunciation: "ri-MISH-un", exampleSentence: "Cancer remission.", synonyms: "Improvement, disappearance", antonyms: "Relapse" },
       { word: "Relapse", definition: "Return of disease", partOfSpeech: "noun", pronunciation: "REE-laps", exampleSentence: "Cancer relapse.", synonyms: "Return, recurrence", antonyms: "Remission" },
       { word: "Morbidity", definition: "State of being diseased", partOfSpeech: "noun", pronunciation: "mor-BID-i-tee", exampleSentence: "Morbidity rate.", synonyms: "Disease burden", antonyms: "Mortality" },
       { word: "Mortality", definition: "Death rate", partOfSpeech: "noun", pronunciation: "mor-TAL-i-tee", exampleSentence: "Infant mortality.", synonyms: "Death rate", antonyms: "Morbidity" },
       { word: "Comorbidity", definition: "Multiple conditions together", partOfSpeech: "noun", pronunciation: "koh-mor-BID-i-tee", exampleSentence: "Comorbid conditions.", synonyms: "Multiple diseases", antonyms: "" },
       { word: "Pathogen", definition: "Disease-causing organism", partOfSpeech: "noun", pronunciation: "PATH-oh-jen", exampleSentence: "Deadly pathogen.", synonyms: "Disease agent", antonyms: "" },
       { word: "Virulence", definition: "Severity of pathogen", partOfSpeech: "noun", pronunciation: "VIR-yoo-lens", exampleSentence: "High virulence.", synonyms: "Severity, harmfulness", antonyms: "Avirulence" },
       { word: "Antibiotic resistance", definition: "Bacteria resisting drugs", partOfSpeech: "noun", pronunciation: "an-ty-by-OT-ik ree-ZIS-tuns", exampleSentence: "Antibiotic resistance crisis.", synonyms: "Drug resistance", antonyms: "" },
       { word: "Placebo", definition: "Inactive substance in trials", partOfSpeech: "noun", pronunciation: "pluh-SEE-boh", exampleSentence: "Placebo effect.", synonyms: "Inert treatment", antonyms: "" },
       { word: "Double-blind", definition: "Study where neither knows", partOfSpeech: "adjective", pronunciation: "DUB-ul blynd", exampleSentence: "Double-blind study.", synonyms: "Controlled trial", antonyms: "" },
       { word: "Cohort", definition: "Group in study", partOfSpeech: "noun", pronunciation: "KOH-hort", exampleSentence: "Study cohort.", synonyms: "Group, sample", antonyms: "" }
       ]
  },
  {
    title: "C2: Advanced Law & Jurisprudence",
    description: "Advanced legal terminology for near-native proficiency",
    level: "C2",
    difficulty: "ADVANCED",
    order: 5,
    xpReward: 30,
    gemReward: 8,
    words: [
       { word: "Jurisprudence", definition: "Philosophy of law", partOfSpeech: "noun", pronunciation: "joor-is-PROO-dens", exampleSentence: "Legal jurisprudence.", synonyms: "Legal theory", antonyms: "" },
       { word: "Plaintiff", definition: "Person who brings case", partOfSpeech: "noun", pronunciation: "PLAYN-tif", exampleSentence: "The plaintiff sued.", synonyms: "Claimant, complainant", antonyms: "Defendant" },
       { word: "Defendant", definition: "Person being sued", partOfSpeech: "noun", pronunciation: "di-FEND-unt", exampleSentence: "The defendant pleaded not guilty.", synonyms: "Accused, respondent", antonyms: "Plaintiff" },
       { word: "Prosecution", definition: "Party bringing criminal case", partOfSpeech: "noun", pronunciation: "pros-i-KYOO-shun", exampleSentence: "The prosecution presented evidence.", synonyms: "Accusers", antonyms: "Defense" },
       { word: "Litigation", definition: "Taking legal action", partOfSpeech: "noun", pronunciation: "lit-i-GAY-shun", exampleSentence: "Civil litigation.", synonyms: "Lawsuit, legal action", antonyms: "" },
       { word: "Jurisdiction", definition: "Authority to hear cases", partOfSpeech: "noun", pronunciation: "joor-is-DIK-shun", exampleSentence: "Court jurisdiction.", synonyms: "Authority, power", antonyms: "" },
       { word: "Statute", definition: "Written law", partOfSpeech: "noun", pronunciation: "STACH-oot", exampleSentence: "Federal statute.", synonyms: "Law, act", antonyms: "" },
       { word: "Precedent", definition: "Earlier case as example", partOfSpeech: "noun", pronunciation: "PRES-i-dunt", exampleSentence: "Legal precedent.", synonyms: "Earlier case", antonyms: "" },
       { word: "Habeas corpus", definition: "Right against unlawful imprisonment", partOfSpeech: "noun", pronunciation: "HAY-bee-us KOR-pus", exampleSentence: "Habeas corpus petition.", synonyms: "", antonyms: "" },
       { word: "Subpoena", definition: "Court order to testify", partOfSpeech: "noun", pronunciation: "suh-PEE-nuh", exampleSentence: "Issue a subpoena.", synonyms: "Court order", antonyms: "" },
       { word: "Testimony", definition: "Statement under oath", partOfSpeech: "noun", pronunciation: "TES-ti-moh-nee", exampleSentence: "Witness testimony.", synonyms: "Evidence, statement", antonyms: "" },
       { word: "Affidavit", definition: "Written sworn statement", partOfSpeech: "noun", pronunciation: "af-i-DAY-vit", exampleSentence: "File an affidavit.", synonyms: "Sworn statement", antonyms: "" },
       { word: "Deposition", definition: "Out-of-court testimony", partOfSpeech: "noun", pronunciation: "dep-oh-ZISH-un", exampleSentence: "Give a deposition.", synonyms: "Sworn testimony", antonyms: "" },
       { word: "Indictment", definition: "Formal criminal charge", partOfSpeech: "noun", pronunciation: "in-DYT-munt", exampleSentence: "Grand jury indictment.", synonyms: "Charge, accusation", antonyms: "" },
       { word: "Acquittal", definition: "Formal release from guilt", partOfSpeech: "noun", pronunciation: "uh-KWIT-ul", exampleSentence: "Verdict of acquittal.", synonyms: "Exoneration", antonyms: "Conviction" },
       { word: "Conviction", definition: "Guilty verdict", partOfSpeech: "noun", pronunciation: "kun-VIK-shun", exampleSentence: "Criminal conviction.", synonyms: "Guilty verdict", antonyms: "Acquittal" },
       { word: "Sentencing", definition: "Pronouncement of punishment", partOfSpeech: "noun", pronunciation: "SENT-un-sing", exampleSentence: "Sentencing hearing.", synonyms: "Punishment", antonyms: "" },
       { word: "Probation", definition: "Supervised release", partOfSpeech: "noun", pronunciation: "proh-BAY-shun", exampleSentence: "On probation.", synonyms: "Supervised release", antonyms: "" },
       { word: "Parole", definition: "Early release from prison", partOfSpeech: "noun", pronunciation: "puh-ROHL", exampleSentence: "Released on parole.", synonyms: "Early release", antonyms: "" },
       { word: "Injunction", definition: "Court order to do/stop", partOfSpeech: "noun", pronunciation: "in-JUNGK-shun", exampleSentence: "Temporary injunction.", synonyms: "Court order", antonyms: "" },
       { word: "Writ", definition: "Formal written order", partOfSpeech: "noun", pronunciation: "rit", exampleSentence: "Writ of mandamus.", synonyms: "Court order", antonyms: "" },
       { word: "Tort", definition: "Civil wrong", partOfSpeech: "noun", pronunciation: "tort", exampleSentence: "Personal injury tort.", synonyms: "Civil wrong", antonyms: "" },
       { word: "Negligence", definition: "Failure to exercise care", partOfSpeech: "noun", pronunciation: "NEG-li-jens", exampleSentence: "Gross negligence.", synonyms: "Carelessness, dereliction", antonyms: "Diligence" },
       { word: "Liability", definition: "Legal responsibility", partOfSpeech: "noun", pronunciation: "ly-uh-BIL-i-tee", exampleSentence: "Product liability.", synonyms: "Responsibility", antonyms: "" },
       { word: "Adjudication", definition: "Formal judgment", partOfSpeech: "noun", pronunciation: "uh-joo-di-KAY-shun", exampleSentence: "Court adjudication.", synonyms: "Judgment, ruling", antonyms: "" },
       { word: "Arbitration", definition: "Settlement by third party", partOfSpeech: "noun", pronunciation: "ar-bi-TRAY-shun", exampleSentence: "Binding arbitration.", synonyms: "Mediation", antonyms: "Litigation" },
       { word: "Mediation", definition: "Negotiated settlement", partOfSpeech: "noun", pronunciation: "mee-dee-AY-shun", exampleSentence: "Court mediation.", synonyms: "Arbitration", antonyms: "Litigation" },
       { word: "Sovereignty", definition: "Supreme power", partOfSpeech: "noun", pronunciation: "SOV-rin-tee", exampleSentence: "National sovereignty.", synonyms: "Supreme authority", antonyms: "" },
       { word: "Constitutional", definition: "Relating to constitution", partOfSpeech: "adjective", pronunciation: "kon-sti-TOO-shun-ul", exampleSentence: "Constitutional law.", synonyms: "", antonyms: "" },
       { word: "Legislation", definition: "Laws collectively", partOfSpeech: "noun", pronunciation: "lej-is-LAY-shun", exampleSentence: "New legislation.", synonyms: "Laws, statutes", antonyms: "" },
       { word: "Regulation", definition: "Rule by authority", partOfSpeech: "noun", pronunciation: "reg-yoo-LAY-shun", exampleSentence: "Government regulations.", synonyms: "Rule, directive", antonyms: "" },
       { word: "Ordinance", definition: "Municipal law", partOfSpeech: "noun", pronunciation: "OR-din-unce", exampleSentence: "City ordinance.", synonyms: "Local law", antonyms: "" },
       { word: "Codification", definition: "Arranging laws into code", partOfSpeech: "noun", pronunciation: "kod-i-fi-KAY-shun", exampleSentence: "Legal codification.", synonyms: "Systematization", antonyms: "" },
       { word: "Statutory", definition: "Relating to statutes", partOfSpeech: "adjective", pronunciation: "STACH-oo-tor-ee", exampleSentence: "Statutory requirement.", synonyms: "Legal, legislative", antonyms: "" },
       { word: "Common law", definition: "Law from customs/court decisions", partOfSpeech: "noun", pronunciation: "KOM-un law", exampleSentence: "English common law.", synonyms: "Case law, precedent", antonyms: "Civil law" },
       { word: "Civil law", definition: "Non-criminal law", partOfSpeech: "noun", pronunciation: "SIV-il law", exampleSentence: "Civil law system.", synonyms: "", antonyms: "Criminal law" },
{ word: "Criminal law", definition: "Law on crimes", partOfSpeech: "noun", pronunciation: "KRIM-in-ul law", exampleSentence: "Criminal law prosecution.", synonyms: "", antonyms: "Civil law" },
       { word: "Tort law", definition: "Civil wrongs law", partOfSpeech: "noun", pronunciation: "tort law", exampleSentence: "Tort law cases.", synonyms: "", antonyms: "" },
       { word: "Contract law", definition: "Agreements law", partOfSpeech: "noun", pronunciation: "KON-trakt law", exampleSentence: "Contract law dispute.", synonyms: "", antonyms: "" },
       { word: "Property law", definition: "Real estate law", partOfSpeech: "noun", pronunciation: "PROP-er-tee law", exampleSentence: "Property law rights.", synonyms: "", antonyms: "" },
       { word: "Intellectual property", definition: "Ideas/inventions ownership", partOfSpeech: "noun", pronunciation: "in-TEL-ek-choo-ul PROP-er-tee", exampleSentence: "Intellectual property rights.", synonyms: "IP rights", antonyms: "" },
       { word: "Copyright", definition: "Right to copy/use work", partOfSpeech: "noun", pronunciation: "KOP-ee-ryt", exampleSentence: "Copyright infringement.", synonyms: "", antonyms: "" },
       { word: "Patent", definition: "Exclusive right to invention", partOfSpeech: "noun", pronunciation: "PAT-unt", exampleSentence: "File a patent.", synonyms: "Exclusive right", antonyms: "" },
       { word: "Trademark", definition: "Protected brand symbol", partOfSpeech: "noun", pronunciation: "TRADE-mark", exampleSentence: "Registered trademark.", synonyms: "Brand protection", antonyms: "" },
     ];
