import { VocabSet } from "../types";

export const frenchA1Data: VocabSet[] = [
  {
    title: "Salutations et Présentations",
    description: "Salutations essentielles et phrases pour se présenter",
    translation: "Greetings & Introductions",
    level: "A1",
    difficulty: "BEGINNER",
    order: 1,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Bonjour", definition: "Salutation utilisée le matin et l'après-midi", translation: "Hello / Good morning", partOfSpeech: "greeting", pronunciation: "bohn-ZHOOR", exampleSentence: "Bonjour, comment allez-vous?", exampleTranslation: "Hello, how are you?", synonyms: "Salut", antonyms: "Bonsoir", difficulty: "EASY", languageCode: "fr" },
      { word: "Bonsoir", definition: "Salutation utilisée le soir", translation: "Good evening", partOfSpeech: "greeting", pronunciation: "bohn-SWAHR", exampleSentence: "Bonsoir, bienvenue!", exampleTranslation: "Good evening, welcome!", synonyms: "", antonyms: "Bonjour", difficulty: "EASY", languageCode: "fr" },
      { word: "Au revoir", definition: "Formule d'adieu", translation: "Goodbye", partOfSpeech: "greeting", pronunciation: "oh reh-VWAHR", exampleSentence: "Au revoir, à bientôt!", exampleTranslation: "Goodbye, see you soon!", synonyms: "Adieu", antonyms: "Bonjour", difficulty: "EASY", languageCode: "fr" },
      { word: "Merci", definition: "Expression de gratitude", translation: "Thank you", partOfSpeech: "greeting", pronunciation: "mehr-SEE", exampleSentence: "Merci beaucoup!", exampleTranslation: "Thank you very much!", synonyms: "Merci beaucoup", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "S'il vous plaît", definition: "Utilisé pour faire une demande polie", translation: "Please", partOfSpeech: "phrase", pronunciation: "seel voo PLEH", exampleSentence: "S'il vous plaît, aidez-moi.", exampleTranslation: "Please, help me.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "De rien", definition: "Réponse polie à merci", translation: "You're welcome", partOfSpeech: "phrase", pronunciation: "deh RYAN", exampleSentence: "De rien, c'est rien.", exampleTranslation: "You're welcome, it's nothing.", synonyms: "Je vous en prie", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Oui", definition: "Réponse affirmative", translation: "Yes", partOfSpeech: "adverb", pronunciation: "wee", exampleSentence: "Oui, je comprends.", exampleTranslation: "Yes, I understand.", synonyms: "", antonyms: "Non", difficulty: "EASY", languageCode: "fr" },
      { word: "Non", definition: "Réponse négative", translation: "No", partOfSpeech: "adverb", pronunciation: "nohn", exampleSentence: "Non, merci.", exampleTranslation: "No, thank you.", synonyms: "", antonyms: "Oui", difficulty: "EASY", languageCode: "fr" },
      { word: "Excusez-moi", definition: "Pour s'excuser ou attirer l'attention", translation: "Excuse me", partOfSpeech: "phrase", pronunciation: "ex-koo-zay-MWAH", exampleSentence: "Excusez-moi, où est la gare?", exampleTranslation: "Excuse me, where is the train station?", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Comment allez-vous?", definition: "Question sur le bien-être", translation: "How are you?", partOfSpeech: "phrase", pronunciation: "koh-MOHN tah-lay VOO", exampleSentence: "Comment allez-vous aujourd'hui?", exampleTranslation: "How are you today?", synonyms: "Comment ça va?", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Je m'appelle", definition: "Pour se présenter", translation: "My name is", partOfSpeech: "phrase", pronunciation: "zhe ma-PELL", exampleSentence: "Je m'appelle Marie.", exampleTranslation: "My name is Marie.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Enchanté", definition: "Formule de politesse en rencontrant quelqu'un", translation: "Nice to meet you", partOfSpeech: "greeting", pronunciation: "on-shon-TAY", exampleSentence: "Enchanté de faire votre connaissance.", exampleTranslation: "Nice to meet you.", synonyms: "Ravi", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Ça va", definition: "Réponse courante sur le bien-être", translation: "I'm fine / It's going", partOfSpeech: "phrase", pronunciation: "sah VAH", exampleSentence: "Ça va bien, merci.", exampleTranslation: "I'm fine, thank you.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Bonne nuit", definition: "Souhait pour la nuit", translation: "Good night", partOfSpeech: "phrase", pronunciation: "bun NWEE", exampleSentence: "Bonne nuit, dors bien!", exampleTranslation: "Good night, sleep well!", synonyms: "", antonyms: "Bonjour", difficulty: "EASY", languageCode: "fr" },
    ]
  },
  {
    title: "Nombres et Temps",
    description: "Nombres de base, jours, mois et expressions temporelles",
    translation: "Numbers & Time",
    level: "A1",
    difficulty: "BEGINNER",
    order: 2,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Un", definition: "Le nombre 1", translation: "One", partOfSpeech: "number", pronunciation: "uhn", exampleSentence: "J'ai un livre.", exampleTranslation: "I have one book.", synonyms: "1", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Deux", definition: "Le nombre 2", translation: "Two", partOfSpeech: "number", pronunciation: "deuh", exampleSentence: "Deux et deux font quatre.", exampleTranslation: "Two plus two is four.", synonyms: "2", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Trois", definition: "Le nombre 3", translation: "Three", partOfSpeech: "number", pronunciation: "twah", exampleSentence: "J'ai trois amis.", exampleTranslation: "I have three friends.", synonyms: "3", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Quatre", definition: "Le nombre 4", translation: "Four", partOfSpeech: "number", pronunciation: "KAT-ruh", exampleSentence: "Il y a quatre saisons.", exampleTranslation: "There are four seasons.", synonyms: "4", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Cinq", definition: "Le nombre 5", translation: "Five", partOfSpeech: "number", pronunciation: "sank", exampleSentence: "J'ai cinq doigts.", exampleTranslation: "I have five fingers.", synonyms: "5", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Six", definition: "Le nombre 6", translation: "Six", partOfSpeech: "number", pronunciation: "seess", exampleSentence: "Il est six heures.", exampleTranslation: "It is six o'clock.", synonyms: "6", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Sept", definition: "Le nombre 7", translation: "Seven", partOfSpeech: "number", pronunciation: "set", exampleSentence: "Sept jours dans une semaine.", exampleTranslation: "Seven days in a week.", synonyms: "7", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Huit", definition: "Le nombre 8", translation: "Eight", partOfSpeech: "number", pronunciation: "weet", exampleSentence: "Huit plus deux font dix.", exampleTranslation: "Eight plus two is ten.", synonyms: "8", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Neuf", definition: "Le nombre 9", translation: "Nine", partOfSpeech: "number", pronunciation: "neuf", exampleSentence: "Neuf mois de grossesse.", exampleTranslation: "Nine months of pregnancy.", synonyms: "9", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Dix", definition: "Le nombre 10", translation: "Ten", partOfSpeech: "number", pronunciation: "deess", exampleSentence: "Dix doigts sur deux mains.", exampleTranslation: "Ten fingers on two hands.", synonyms: "10", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Lundi", definition: "Premier jour de la semaine", translation: "Monday", partOfSpeech: "noun", pronunciation: "LUN-dee", exampleSentence: "Je travaille lundi.", exampleTranslation: "I work on Monday.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Mardi", definition: "Deuxième jour de la semaine", translation: "Tuesday", partOfSpeech: "noun", pronunciation: "TAR-dee", exampleSentence: "Mardi vient après lundi.", exampleTranslation: "Tuesday comes after Monday.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Mercredi", definition: "Troisième jour de la semaine", translation: "Wednesday", partOfSpeech: "noun", pronunciation: "mare-kruh-DEE", exampleSentence: "Mercredi est au milieu de la semaine.", exampleTranslation: "Wednesday is in the middle of the week.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Jeudi", definition: "Quatrième jour de la semaine", translation: "Thursday", partOfSpeech: "noun", pronunciation: "ZHEU-dee", exampleSentence: "Jeudi est presque vendredi.", exampleTranslation: "Thursday is almost Friday.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Vendredi", definition: "Cinquième jour de la semaine", translation: "Friday", partOfSpeech: "noun", pronunciation: "von-druh-DEE", exampleSentence: "Vendredi est mon jour préféré.", exampleTranslation: "Friday is my favorite day.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Samedi", definition: "Sixième jour de la semaine", translation: "Saturday", partOfSpeech: "noun", pronunciation: "sam-DEE", exampleSentence: "Je fais les courses samedi.", exampleTranslation: "I go shopping on Saturday.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Dimanche", definition: "Septième jour de la semaine", translation: "Sunday", partOfSpeech: "noun", pronunciation: "dee-MONSH", exampleSentence: "Dimanche est un jour de repos.", exampleTranslation: "Sunday is a rest day.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Aujourd'hui", definition: "Le jour actuel", translation: "Today", partOfSpeech: "noun", pronunciation: "oh-zhoor-DWEE", exampleSentence: "Aujourd'hui est lundi.", exampleTranslation: "Today is Monday.", synonyms: "Ce jour", antonyms: "Hier", difficulty: "EASY", languageCode: "fr" },
      { word: "Demain", definition: "Le jour après aujourd'hui", translation: "Tomorrow", partOfSpeech: "noun", pronunciation: "duh-MAN", exampleSentence: "Demain est mon anniversaire.", exampleTranslation: "Tomorrow is my birthday.", synonyms: "", antonyms: "Hier", difficulty: "EASY", languageCode: "fr" },
      { word: "Hier", definition: "Le jour avant aujourd'hui", translation: "Yesterday", partOfSpeech: "noun", pronunciation: "YERE", exampleSentence: "Hier était dimanche.", exampleTranslation: "Yesterday was Sunday.", synonyms: "", antonyms: "Demain", difficulty: "EASY", languageCode: "fr" },
    ]
  },
  {
    title: "La Famille et les Amis",
    description: "Mots liés à la famille et aux amis",
    translation: "Family & Friends",
    level: "A1",
    difficulty: "BEGINNER",
    order: 3,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Père", definition: "Homme qui a engendré un enfant", translation: "Father", partOfSpeech: "noun", pronunciation: "PAIR", exampleSentence: "Mon père est à la maison.", exampleTranslation: "My father is at home.", synonyms: "Papa", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Mère", definition: "Femme qui a donné naissance à un enfant", translation: "Mother", partOfSpeech: "noun", pronunciation: "MAIR", exampleSentence: "Ma mère est professeur.", exampleTranslation: "My mother is a teacher.", synonyms: "Maman", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Enfant", definition: "Être humain jeune", translation: "Child", partOfSpeech: "noun", pronunciation: "on-FON", exampleSentence: "L'enfant est à la maison.", exampleTranslation: "The child is at home.", synonyms: "Gamin", antonyms: "Adulte", difficulty: "EASY", languageCode: "fr" },
      { word: "Frère", definition: "Garçon né des mêmes parents", translation: "Brother", partOfSpeech: "noun", pronunciation: "FRERE", exampleSentence: "Mon frère va à l'école.", exampleTranslation: "My brother goes to school.", synonyms: "", antonyms: "Sœur", difficulty: "EASY", languageCode: "fr" },
      { word: "Sœur", definition: "Fille née des mêmes parents", translation: "Sister", partOfSpeech: "noun", pronunciation: "SEUR", exampleSentence: "Ma sœur est médecin.", exampleTranslation: "My sister is a doctor.", synonyms: "", antonyms: "Frère", difficulty: "EASY", languageCode: "fr" },
      { word: "Ami", definition: "Personne avec qui on a une relation amicale", translation: "Friend (male)", partOfSpeech: "noun", pronunciation: "ah-MEE", exampleSentence: "Mon ami est là.", exampleTranslation: "My friend is there.", synonyms: "", antonyms: "Ennemi", difficulty: "EASY", languageCode: "fr" },
      { word: "Amie", definition: "Femme avec qui on a une relation amicale", translation: "Friend (female)", partOfSpeech: "noun", pronunciation: "ah-MEE", exampleSentence: "Mon amie est française.", exampleTranslation: "My friend is French.", synonyms: "", antonyms: "Ennemie", difficulty: "EASY", languageCode: "fr" },
      { word: "Mari", definition: "Homme marié", translation: "Husband", partOfSpeech: "noun", pronunciation: "mah-REE", exampleSentence: "Mon mari est docteur.", exampleTranslation: "My husband is a doctor.", synonyms: "", antonyms: "Femme", difficulty: "EASY", languageCode: "fr" },
      { word: "Femme", definition: "Femme mariée", translation: "Wife", partOfSpeech: "noun", pronunciation: "FAM", exampleSentence: "Ma femme est infirmière.", exampleTranslation: "My wife is a nurse.", synonyms: "", antonyms: "Mari", difficulty: "EASY", languageCode: "fr" },
      { word: "Famille", definition: "Groupe de personnes liées par le sang", translation: "Family", partOfSpeech: "noun", pronunciation: "fah-MEEY", exampleSentence: "Ma famille est grande.", exampleTranslation: "My family is big.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
    ]
  },
  {
    title: "Le Corps Humain",
    description: "Mots liés aux parties du corps",
    translation: "Body Parts",
    level: "A1",
    difficulty: "BEGINNER",
    order: 4,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Tête", definition: "Partie supérieure du corps", translation: "Head", partOfSpeech: "noun", pronunciation: "TET", exampleSentence: "Ma tête me fait mal.", exampleTranslation: "My head hurts.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Œil", definition: "Organe de la vision", translation: "Eye", partOfSpeech: "noun", pronunciation: "EU-yuh", exampleSentence: "Mes yeux sont bleus.", exampleTranslation: "My eyes are blue.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Oreille", definition: "Organe de l'audition", translation: "Ear", partOfSpeech: "noun", pronunciation: "oh-REY", exampleSentence: "Mes oreilles me font mal.", exampleTranslation: "My ears hurt.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Nez", definition: "Organe de l'odorat", translation: "Nose", partOfSpeech: "noun", pronunciation: "nay", exampleSentence: "Mon nez est grand.", exampleTranslation: "My nose is big.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Bouche", definition: "Ouverture du visage pour manger et parler", translation: "Mouth", partOfSpeech: "noun", pronunciation: "BOOSH", exampleSentence: "Ma bouche me fait mal.", exampleTranslation: "My mouth hurts.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Main", definition: "Partie du corps pour tenir et toucher", translation: "Hand", partOfSpeech: "noun", pronunciation: "man", exampleSentence: "Ma main est grande.", exampleTranslation: "My hand is big.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Pied", definition: "Partie du corps pour marcher", translation: "Foot", partOfSpeech: "noun", pronunciation: "pye", exampleSentence: "Mon pied me fait mal.", exampleTranslation: "My foot hurts.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Ventre", definition: "Partie du corps où se trouve l'estomac", translation: "Stomach", partOfSpeech: "noun", pronunciation: "VON-truh", exampleSentence: "Mon ventre me fait mal.", exampleTranslation: "My stomach hurts.", synonyms: "Estomac", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Cœur", definition: "Organe qui pompe le sang", translation: "Heart", partOfSpeech: "noun", pronunciation: "KEUR", exampleSentence: "Mon cœur bat.", exampleTranslation: "My heart is beating.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Dos", definition: "Partie arrière du corps", translation: "Back", partOfSpeech: "noun", pronunciation: "doh", exampleSentence: "Mon dos me fait mal.", exampleTranslation: "My back hurts.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
    ]
  },
  {
    title: "Les Couleurs",
    description: "Mots liés aux couleurs de base",
    translation: "Colors",
    level: "A1",
    difficulty: "BEGINNER",
    order: 5,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Blanc", definition: "Couleur comme la neige ou le lait", translation: "White", partOfSpeech: "adjective", pronunciation: "blon", exampleSentence: "Ce vêtement blanc est beau.", exampleTranslation: "This white cloth is nice.", synonyms: "", antonyms: "Noir", difficulty: "EASY", languageCode: "fr" },
      { word: "Noir", definition: "Couleur comme la nuit ou le charbon", translation: "Black", partOfSpeech: "adjective", pronunciation: "nwahr", exampleSentence: "L'homme noir est là.", exampleTranslation: "The black man is there.", synonyms: "", antonyms: "Blanc", difficulty: "EASY", languageCode: "fr" },
      { word: "Rouge", definition: "Couleur comme le sang ou la tomate", translation: "Red", partOfSpeech: "adjective", pronunciation: "roozh", exampleSentence: "Ce vêtement rouge est beau.", exampleTranslation: "This red cloth is nice.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Jaune", definition: "Couleur comme le soleil ou le citron", translation: "Yellow", partOfSpeech: "adjective", pronunciation: "zhone", exampleSentence: "Le soleil est jaune.", exampleTranslation: "The sun is yellow.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Vert", definition: "Couleur comme l'herbe ou les feuilles", translation: "Green", partOfSpeech: "adjective", pronunciation: "vair", exampleSentence: "L'arbre vert est là.", exampleTranslation: "The green tree is there.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Bleu", definition: "Couleur comme le ciel ou l'océan", translation: "Blue", partOfSpeech: "adjective", pronunciation: "bleuh", exampleSentence: "Ce vêtement bleu est beau.", exampleTranslation: "This blue cloth is nice.", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "fr" },
      { word: "Marron", definition: "Couleur comme la terre ou le bois", translation: "Brown", partOfSpeech: "noun", pronunciation: "mah-ROHN", exampleSentence: "Le sol est marron.", exampleTranslation: "The ground is brown.", synonyms: "", antonyms: "", difficulty: "MEDIUM", languageCode: "fr" },
      { word: "Rose", definition: "Couleur comme la chair ou les fleurs", translation: "Pink", partOfSpeech: "adjective", pronunciation: "rohz", exampleSentence: "Ce vêtement rose est beau.", exampleTranslation: "This pink cloth is nice.", synonyms: "", antonyms: "", difficulty: "MEDIUM", languageCode: "fr" },
      { word: "Gris", definition: "Couleur comme la cendre", translation: "Gray", partOfSpeech: "adjective", pronunciation: "gree", exampleSentence: "Le ciel est gris.", exampleTranslation: "The sky is gray.", synonyms: "", antonyms: "", difficulty: "MEDIUM", languageCode: "fr" },
    ]
  },
];
