const expandAndAppend = require('./expand-vocab-lib');

const data = [
  ["Supply Chain Optimization", "Efficiency in product flow", "Just-in-time|Inventory arrives only as needed|noun|just in tym|Adopt just-in-time.|efficient inventory|;Lean manufacturing|Systematic method for waste minimization|noun|leen man-yuh-FAK-cher-ing|Lean manufacturing principles.|waste reduction|;Six Sigma|Techniques for process improvement|noun|siks SIG-muh|Implement Six Sigma.|quality management|;Bottleneck|Point of congestion in a system|noun|BOT-ul-nek|Identify the bottleneck.|choke point|;Bullwhip effect|Increasing swings in inventory in response to demand|noun|BOOL-whip i-FEKT|Avoid the bullwhip effect.|demand fluctuation|;Lead time|Latency between initiation and completion|noun|leed tym|Reduce lead time.|processing time|;Inventory turnover|Number of times stock is sold and replaced|noun|IN-vuhn-tor-ee TURN-oh-ver|High inventory turnover.|stock rotation|;Strategic sourcing|Procurement process that focuses on long-term goals|noun|struh-TEE-jik SOR-sing|Improve strategic sourcing.|smart purchasing|;Outsourcing|Obtaining goods from an outside supplier|noun|OUT-sor-sing|Outsourcing logistics.|contracting out|;Third-party logistics|Using outside providers for distribution|noun|therd PAR-tee loh-JIS-tiks|Hire a 3PL provider.|3PL|;Cross-docking|Transferring goods directly from inbound to outbound|noun|kros DOK-ing|Efficient cross-docking.|direct transfer|;Warehousing|Action of storing goods in a warehouse|noun|WAIR-hou-zing|Modern warehousing.|storage|;Last-mile delivery|Final step of the delivery process|noun|last-myl di-LIV-er-ee|Optimize last-mile delivery.|final delivery|;Sustainability|Responsibility for environmental impact|noun|suh-stay-nuh-BIL-i-tee|Supply chain sustainability.|green logistics|;Cold chain|Temperature-controlled supply chain|noun|kohld chayn|Vaccine cold chain.|refrigerated logistics|"],
  ["Public Administration", "Governance and societal management", "Bureaucracy|System of government with many departments|noun|byoo-ROK-ruh-see|Reduce bureaucracy.|red tape|;Governance|Action or manner of governing|noun|GUV-er-nuhns|Improve local governance.|ruling|;Public policy|Principles of action adopted by government|noun|PUB-lik POL-i-see|Economic public policy.|strategy|;Civic engagement|Individual and group actions for public good|noun|SIV-ik en-GAYJ-muhnt|Promote civic engagement.|involvement|;Legislative branch|Branch of government that makes laws|noun|LEJ-is-lay-tiv branch|The legislative branch.|parliament|;Executive branch|Branch of government that enforces laws|noun|ig-ZEK-yoo-tiv branch|The executive branch.|administration|;Judicial branch|Branch of government that interprets laws|noun|joo-DISH-ul branch|The judicial branch.|courts|;Constitution|Fundamental principles of a state|noun|kon-sti-TOO-shuhn|Protect the constitution.|supreme law|;Democracy|Government by the people|noun|di-MOK-ruh-see|Democratic elections.|people's rule|;Regulation|Rule or directive maintained by authority|noun|reg-yuh-LAY-shuhn|Safety regulation.|rule|;Public sector|Part of the economy controlled by government|noun|PUB-lik SEK-ter|Public sector jobs.|government sector|private sector;Fiscal policy|Government spending and taxation|noun|FIS-kuhl POL-i-see|Manage fiscal policy.|tax policy|;Taxation|Levying of tax|noun|tak-SAY-shuhn|Direct taxation.|levy|;Budgeting|Planning how to spend money|noun|BUJ-et-ing|Annual budgeting.|financial planning|;Social welfare|Government support for citizens|noun|SOH-shul WEL-fair|Social welfare programs.|public support|"],
  ["Environmental Conservation", "Protecting the natural world", "Biodiversity|Variety of species in an ecosystem|noun|by-oh-di-VER-si-tee|Protect biodiversity.|variety|;Ecosystem|Biological community of interacting organisms|noun|EE-koh-sis-tuhm|Forest ecosystem.|nature system|;Endangered species|Species at risk of extinction|noun|en-DAYN-jerd SPEE-sheez|Save endangered species.|at-risk species|;Habitat|Natural home of an organism|noun|HAB-i-tat|Protect animal habitat.|natural home|;Reforestation|Planting trees in an area where there were none|noun|ree-for-es-TAY-shun|Reforestation efforts.|tree planting|deforestation;Sustainable|Able to be maintained at a certain level|adjective|suh-STAY-nuh-buhl|Sustainable practices.|long-term|;Conservation|Protecting natural resources|noun|kon-ser-VAY-shun|Wildlife conservation.|protection|;Pollution|Presence of harmful substances in environment|noun|puh-LOO-shun|Air pollution.|contamination|;Climate change|Long-term shift in weather patterns|noun|KLY-mit chaynj|Combat climate change.|global warming|;Renewable energy|Energy from natural sources|noun|ri-NOO-uh-buhl EN-er-jee|Solar renewable energy.|green energy|fossil fuels;Carbon footprint|Total greenhouse gas emissions|noun|KAR-bun FOOT-print|Reduce your carbon footprint.|impact|;Waste management|Handling and disposing of waste|noun|wayst MAN-ij-muhnt|Effective waste management.|disposal|;Composting|Decomposing organic matter|noun|KOM-poh-sting|Start composting.|organic recycling|;Greenhouse effect|Heat trapped in Earth's atmosphere|noun|GREEN-hous i-FEKT|Study the greenhouse effect.|warming|;Ecology|Study of organisms and their environment|noun|ee-KOL-uh-jee|Advanced ecology.|nature study|"]
];

data.forEach(d => expandAndAppend({
  level: 'B2',
  title: d[0],
  description: d[1],
  difficulty: 'INTERMEDIATE',
  words: d[2]
}));
