import { VocabSet } from "../types";

export const yorubaA1Data: VocabSet[] = [
  {
    title: "Àwọn Ìkíni àti Ìsopọ̀",
    description: "Àwọn ìkíni pàtàkì àti àwọn gbólóhùn fún kíkópa ara ẹni",
    translation: "Greetings & Introductions",
    level: "A1",
    difficulty: "BEGINNER",
    order: 1,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Ẹ̀ nlá", definition: "Ìkíni tí a máa ń lò ní òwúrọ̀", translation: "Good morning", partOfSpeech: "greeting", pronunciation: "eh N-LA", exampleSentence: "Ẹ̀ nlá, kí ni àwọn rẹ̀?", exampleTranslation: "Good morning, how are you?", synonyms: "Ẹ̀ kúùtù", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Kí nǐ", definition: "Ìbéèrè nípa bí ẹnikan ṣe wà", translation: "How are you?", partOfSpeech: "greeting", pronunciation: "keh nee", exampleSentence: "Kí nǐ sẹ̀?", exampleTranslation: "How are you doing?", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Moòdímú", definition: "Ìdáhùn tí ó fi hàn pé ènìyàn wà dáadáa", translation: "I am fine", partOfSpeech: "response", pronunciation: "moh-OH-dee-moo", exampleSentence: "Moòdímú, óòrùn", exampleTranslation: "I am fine, thank you", synonyms: "Mo wà dáadáa", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ẹ kúrọ̀", definition: "Ọ̀rọ̀ ìdúpẹ́ fún ohun tí wọ́n ṣe", translation: "Thank you", partOfSpeech: "greeting", pronunciation: "eh KOO-ro", exampleSentence: "Ẹ kúrọ̀ nǐu!", exampleTranslation: "Thank you very much!", synonyms: "Ẹ̀ sé", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọ̀la ọ̀nà", definition: "Ìkíni tí a máa ń lò ní ọ̀sán", translation: "Good afternoon", partOfSpeech: "greeting", pronunciation: "OH-la OH-na", exampleSentence: "Ọ̀la ọ̀nà, ẹ kú iṣẹ́", exampleTranslation: "Good afternoon, well done with your work", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ẹ̀kùọ́", definition: "Ìkíni tí a máa ń lò ní rọ̀lẹ́", translation: "Good evening", partOfSpeech: "greeting", pronunciation: "eh-KOO-ro", exampleSentence: "Ẹ̀kùọ́, ẹ kú iṣẹ́", exampleTranslation: "Good evening, well done with your work", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ìrìn àti", definition: "Ọ̀rọ̀ ìsìnkú tí a máa ń lò nígbà tí a bá ń lọ", translation: "Goodbye", partOfSpeech: "greeting", pronunciation: "ee-ree-N ah-tee", exampleSentence: "Ìrìn àti, máa sì wá síbí", exampleTranslation: "Goodbye, come back here", synonyms: "Ó di tí tán", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Báwo ni", definition: "Ìbéèrè nípa bí ẹnikan ṣe wà", translation: "How do you do?", partOfSpeech: "greeting", pronunciation: "BAH-woh nee", exampleSentence: "Báwo ni, báwo ni ọjọ́ rẹ?", exampleTranslation: "How do you do, how was your day?", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Jọ̀wọ́", definition: "Ọ̀rọ̀ tí a máa ń lò fún ẹ̀bẹ̀ tàbí ọmọ̀rùn", translation: "Please", partOfSpeech: "adverb", pronunciation: "JOH-woh", exampleSentence: "Jọ̀wọ́, fún mi ní omi", exampleTranslation: "Please, give me water", synonyms: "Ẹ jọ̀wọ́", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ẹ jọ̀wọ́", definition: "Ọ̀rọ̀ ìbéèrè tí a fi ń bẹ ọmọ̀rùn", translation: "Please (plural)", partOfSpeech: "adverb", pronunciation: "EH JOH-woh", exampleSentence: "Ẹ jọ̀wọ́, ẹ gbọ́ mi", exampleTranslation: "Please, listen to me", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "E̩ ṣeun", definition: "Ọ̀rọ̀ ìdúpẹ́ kékeré", translation: "Thank you (casual)", partOfSpeech: "greeting", pronunciation: "EH sheh-oon", exampleSentence: "E̩ ṣeun fún ìrànlọ́wọ́ rẹ", exampleTranslation: "Thank you for your help", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Bẹ́ẹ̀ni", definition: "Ìdáhùn tí ó fi hàn pé à ń fọwọ́ sí nǹkan", translation: "Yes", partOfSpeech: "adverb", pronunciation: "BEH-eh-nee", exampleSentence: "Bẹ́ẹ̀ni, mo fẹ́ lọ síbẹ̀", exampleTranslation: "Yes, I want to go there", synonyms: "", antonyms: "Bẹ́ẹ̀kọ́", difficulty: "EASY", languageCode: "yo" },
      { word: "Bẹ́ẹ̀kọ́", definition: "Ìdáhùn tí ó fi hàn pé à kò fọwọ́ sí nǹkan", translation: "No", partOfSpeech: "adverb", pronunciation: "BEH-eh-koh", exampleSentence: "Bẹ́ẹ̀kọ́, n kò fẹ́ lọ", exampleTranslation: "No, I don't want to go", synonyms: "", antonyms: "Bẹ́ẹ̀ni", difficulty: "EASY", languageCode: "yo" },
      { word: "Kí l'o máa ń ṣe?", definition: "Ìbéèrè nípa iṣẹ́ tàbí nǹkan tí ẹnikan ń ṣe", translation: "What do you do?", partOfSpeech: "phrase", pronunciation: "kee lo MAH N sheh", exampleSentence: "Kí l'o máa ń ṣe? Mo jẹ́ ọmọ̀wé", exampleTranslation: "What do you do? I am a student", synonyms: "", antonyms: "", difficulty: "MEDIUM", languageCode: "yo" },
      { word: "Orúkọ mi ni", definition: "Gbólóhùn tí a fi ń kópa ara ẹni", translation: "My name is", partOfSpeech: "phrase", pronunciation: "oh-ROO-koh mee nee", exampleSentence: "Orúkọ mi ni Adéọlá", exampleTranslation: "My name is Adéọlá", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Àárọ̀", definition: "Àkókò tí ó wà ní ìbẹ̀rẹ̀ ọjọ́", translation: "Morning", partOfSpeech: "noun", pronunciation: "ah-AH-roh", exampleSentence: "Mo máa ń jẹun ní àárọ̀", exampleTranslation: "I eat in the morning", synonyms: "Òwúrọ̀", antonyms: "Ìrọ̀lẹ́", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọ̀sán", definition: "Àkókò tí ó wà ní àárín ọjọ́", translation: "Afternoon", partOfSpeech: "noun", pronunciation: "OH-san", exampleSentence: "Ọ̀sán ti ni tán", exampleTranslation: "The afternoon is over", synonyms: "", antonyms: "Àárọ̀", difficulty: "EASY", languageCode: "yo" },
      { word: "Ìrọ̀lẹ́", definition: "Àkókò tí ó wà ní ìparí ọjọ́", translation: "Evening", partOfSpeech: "noun", pronunciation: "ee-ROH-leh", exampleSentence: "Ìrọ̀lẹ́ dára fún ìsinmi", exampleTranslation: "Evening is good for rest", synonyms: "Alẹ́", antonyms: "Àárọ̀", difficulty: "EASY", languageCode: "yo" },
      { word: "Alẹ́", definition: "Àkókò tí ó wà lẹ́yìn ìrọ̀lẹ́", translation: "Night", partOfSpeech: "noun", pronunciation: "ah-LEH", exampleSentence: "Mo sùn ní alẹ́", exampleTranslation: "I sleep at night", synonyms: "", antonyms: "Ọ̀sán", difficulty: "EASY", languageCode: "yo" },
      { word: "Ó dàrúkọ", definition: "Ìbéèrè nípa orúkọ ẹnikan", translation: "What is your name?", partOfSpeech: "phrase", pronunciation: "OH dah-roo-koh", exampleSentence: "Ó dàrúkọ? Orúkọ mi ni Tọlú", exampleTranslation: "What is your name? My name is Tọlú", synonyms: "Kí ni orúkọ rẹ?", antonyms: "", difficulty: "MEDIUM", languageCode: "yo" },
    ]
  },
  {
    title: "Àwọn Nọ́mbà àti Àkókò",
    description: "Àwọn nọ́mbà ìpìlẹ̀, ọjọ́ ọsẹ̀, oṣù, àti àwọn gbólóhùn àkókò",
    translation: "Numbers & Time",
    level: "A1",
    difficulty: "BEGINNER",
    order: 2,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Ọ̀kan", definition: "Nọ́mbà kejìlélógún", translation: "One", partOfSpeech: "number", pronunciation: "OH-kan", exampleSentence: "Mo ní ọ̀kan péré", exampleTranslation: "I have only one", synonyms: "1", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Méjì", definition: "Nọ́mbà kejì", translation: "Two", partOfSpeech: "number", pronunciation: "MEH-jee", exampleSentence: "Méjì lọ́wọ́ mi", exampleTranslation: "I have two in my hand", synonyms: "2", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Mẹ́ta", definition: "Nọ́mbà kẹta", translation: "Three", partOfSpeech: "number", pronunciation: "MEH-ta", exampleSentence: "Mẹ́ta ni wọ́n wà", exampleTranslation: "They are three in number", synonyms: "3", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Mẹ́rin", definition: "Nọ́mbà kẹrin", translation: "Four", partOfSpeech: "number", pronunciation: "MEH-reen", exampleSentence: "Mẹ́rin ni ọmọ rẹ̀", exampleTranslation: "He has four children", synonyms: "4", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Márùn-ún", definition: "Nọ́mbà karùn-ún", translation: "Five", partOfSpeech: "number", pronunciation: "MAH-roon-un", exampleSentence: "Márùn-ún ni wọ́n wà níbẹ̀", exampleTranslation: "There are five of them there", synonyms: "5", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Mẹ́fà", definition: "Nọ́mbà kẹfà", translation: "Six", partOfSpeech: "number", pronunciation: "MEH-fa", exampleSentence: "Mẹ́fà lọ́wọ́ mi", exampleTranslation: "I have six", synonyms: "6", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Mẹ́je", definition: "Nọ́mbà keje", translation: "Seven", partOfSpeech: "number", pronunciation: "MEH-jeh", exampleSentence: "Ọjọ́ mẹ́je ni wọ́n ti lọ", exampleTranslation: "Seven days have passed", synonyms: "7", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Mẹ́jọ", definition: "Nọ́mbà kejọ", translation: "Eight", partOfSpeech: "number", pronunciation: "MEH-joh", exampleSentence: "Mẹ́jọ ni wọ́n wà", exampleTranslation: "They are eight in number", synonyms: "8", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Mẹ́sàn-án", definition: "Nọ́mbà kẹsàn-án", translation: "Nine", partOfSpeech: "number", pronunciation: "MEH-san-an", exampleSentence: "Mẹ́sàn-án ni wọ́n wà", exampleTranslation: "They are nine in number", synonyms: "9", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Mẹ́wàá", definition: "Nọ́mbà kẹ̀wàá", translation: "Ten", partOfSpeech: "number", pronunciation: "MEH-waa", exampleSentence: "Mẹ́wàá ni wọ́n wà", exampleTranslation: "They are ten in number", synonyms: "10", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọjọ́ Àjé", definition: "Ọjọ́ àkọ́kọ́ ti ọ̀sẹ̀", translation: "Monday", partOfSpeech: "noun", pronunciation: "OH-joh AH-jeh", exampleSentence: "Mo ṣiṣẹ́ Ọjọ́ Àjé", exampleTranslation: "I work on Monday", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọjọ́ Ìṣégun", definition: "Ọjọ́ kejì ti ọ̀sẹ̀", translation: "Tuesday", partOfSpeech: "noun", pronunciation: "OH-joh ee-SHEH-goon", exampleSentence: "Ọjọ́ Ìṣégun tó gbà á", exampleTranslation: "Tuesday that he came", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọjọ́rú", definition: "Ọjọ́ kẹta ti ọ̀sẹ̀", translation: "Wednesday", partOfSpeech: "noun", pronunciation: "OH-joh-roo", exampleSentence: "Ọjọ́rú jẹ́ ọjọ́ arọ́", exampleTranslation: "Wednesday is market day", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọjọ́bọ", definition: "Ọjọ́ kẹrin ti ọ̀sẹ̀", translation: "Thursday", partOfSpeech: "noun", pronunciation: "OH-joh-boh", exampleSentence: "Ọjọ́bọ ni wọ́n máa ń lọ sí ibi ayẹyẹ", exampleTranslation: "They go to the party on Thursday", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọjọ́ Ẹtì", definition: "Ọjọ́ kẹfa ti ọ̀sẹ̀", translation: "Friday", partOfSpeech: "noun", pronunciation: "OH-joh EH-tee", exampleSentence: "Ọjọ́ Ẹtì jẹ́ ọjọ́ ìsinmi", exampleTranslation: "Friday is a rest day", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọjọ́ Àbámẹ́ta", definition: "Ọjọ́ keje ti ọ̀sẹ̀", translation: "Saturday", partOfSpeech: "noun", pronunciation: "OH-joh ah-BAH-meh-ta", exampleSentence: "Ọjọ́ Àbámẹ́ta ni wọ́n máa ń wà nílé", exampleTranslation: "They stay at home on Saturday", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọjọ́ Àìkú", definition: "Ọjọ́ kẹjọ ti ọ̀sẹ̀", translation: "Sunday", partOfSpeech: "noun", pronunciation: "OH-joh ah-ee-KOO", exampleSentence: "Ọjọ́ Àìkú jẹ́ ọjọ́ ìsìn", exampleTranslation: "Sunday is a worship day", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Òní", definition: "Ọjọ́ tó wà ní hùhù", translation: "Today", partOfSpeech: "noun", pronunciation: "OH-nee", exampleSentence: "Òní ni ọjọ́ Àjé", exampleTranslation: "Today is Monday", synonyms: "Ọjọ́ yìí", antonyms: "Àná", difficulty: "EASY", languageCode: "yo" },
      { word: "Òla", definition: "Ọjọ́ tó ń bọ̀ lọ́wọ́lọ́wọ́", translation: "Tomorrow", partOfSpeech: "noun", pronunciation: "OH-la", exampleSentence: "Òla ni wọ́n máa ń lọ", exampleTranslation: "They will go tomorrow", synonyms: "", antonyms: "Àná", difficulty: "EASY", languageCode: "yo" },
      { word: "Àná", definition: "Ọjọ́ tó kọjá", translation: "Yesterday", partOfSpeech: "noun", pronunciation: "AH-na", exampleSentence: "Àná ni wọ́n ti lọ", exampleTranslation: "They went yesterday", synonyms: "", antonyms: "Òní", difficulty: "EASY", languageCode: "yo" },
    ]
  },
  {
    title: "Ẹbí àti Àwọn Ọ̀rẹ́",
    description: "Àwọn ọ̀rọ̀ tí ó jẹ́ mọ́ ẹbí àti àwọn ọ̀rẹ́",
    translation: "Family & Friends",
    level: "A1",
    difficulty: "BEGINNER",
    order: 3,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Bàbá", definition: "Ọkùnrin tí ó bí ọmọ", translation: "Father", partOfSpeech: "noun", pronunciation: "BAH-ba", exampleSentence: "Bàbá mi wà nílé", exampleTranslation: "My father is at home", synonyms: "Papa", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Màmá", definition: "Obìnrin tí ó bí ọmọ", translation: "Mother", partOfSpeech: "noun", pronunciation: "MAH-ma", exampleSentence: "Màmá mi jẹ́ olùkọ́", exampleTranslation: "My mother is a teacher", synonyms: "Mama", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọmọ", definition: "Ẹnìyàn tí a bí", translation: "Child", partOfSpeech: "noun", pronunciation: "OH-moh", exampleSentence: "Ọmọ rẹ̀ wà nílé", exampleTranslation: "His child is at home", synonyms: "Ọmọdé", antonyms: "Àgbàlagbà", difficulty: "EASY", languageCode: "yo" },
      { word: "Ẹ̀gbọ́n", definition: "Ẹnìyàn tó tóbi ní ẹbí", translation: "Older sibling", partOfSpeech: "noun", pronunciation: "EH-gbohn", exampleSentence: "Ẹ̀gbọ́n mi ń lọ sí ilé ẹ̀kọ́", exampleTranslation: "My older sibling is going to school", synonyms: "", antonyms: "Àbúrò", difficulty: "EASY", languageCode: "yo" },
      { word: "Àbúrò", definition: "Ẹnìyàn tó kéré ní ẹbí", translation: "Younger sibling", partOfSpeech: "noun", pronunciation: "ah-BOO-roh", exampleSentence: "Àbúrò mi jẹ́ ọmọdé", exampleTranslation: "My younger sibling is a child", synonyms: "", antonyms: "Ẹ̀gbọ́n", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọkùnrin", definition: "Eniyan ti o je akọ", translation: "Man", partOfSpeech: "noun", pronunciation: "OH-koo-ree", exampleSentence: "Ọkùnrin naa wà níbẹ̀", exampleTranslation: "The man is there", synonyms: "Okunrin", antonyms: "Obìnrin", difficulty: "EASY", languageCode: "yo" },
      { word: "Obìnrin", definition: "Eniyan ti o je abo", translation: "Woman", partOfSpeech: "noun", pronunciation: "oh-BEE-nee", exampleSentence: "Obìnrin naa jẹ́ oníṣòwò", exampleTranslation: "The woman is a trader", synonyms: "Obinrin", antonyms: "Ọkùnrin", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọ̀rẹ́", definition: "Ẹnìyàn tí a ní àjọṣe pẹ̀lú", translation: "Friend", partOfSpeech: "noun", pronunciation: "OH-reh", exampleSentence: "Ọ̀rẹ́ mi wà níbẹ̀", exampleTranslation: "My friend is there", synonyms: "", antonyms: "Ọtá", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọkọ", definition: "Ọkùnrin tí obìnrin gbé", translation: "Husband", partOfSpeech: "noun", pronunciation: "OH-koh", exampleSentence: "Ọkọ mi jẹ́ dókítà", exampleTranslation: "My husband is a doctor", synonyms: "", antonyms: "Aya", difficulty: "EASY", languageCode: "yo" },
      { word: "Aya", definition: "Obìnrin tí ọkùnrin gbé", translation: "Wife", partOfSpeech: "noun", pronunciation: "AH-ya", exampleSentence: "Aya mi jẹ́ olùṣọ́", exampleTranslation: "My wife is a nurse", synonyms: "", antonyms: "Ọkọ", difficulty: "EASY", languageCode: "yo" },
      { word: "Àgbàlagbà", definition: "Ẹnìyàn tó ti darúgbó", translation: "Elder", partOfSpeech: "noun", pronunciation: "ah-GBA-la-gba", exampleSentence: "Àgbàlagbà yìí jẹ́ ọmọ bíbí", exampleTranslation: "This elder is very wise", synonyms: "Alàgbà", antonyms: "Ọmọdé", difficulty: "MEDIUM", languageCode: "yo" },
      { word: "Ìyá", definition: "Șókí ìpe fún màmá", translation: "Mom", partOfSpeech: "noun", pronunciation: "EE-ya", exampleSentence: "Ìyá mi fẹ́ràn mi", exampleTranslation: "My mom loves me", synonyms: "Màmá", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Bàbá mi", definition: "Șókí ìpe fún bàbá", translation: "Dad", partOfSpeech: "noun", pronunciation: "BAH-ba mee", exampleSentence: "Bàbá mi lọ sí ibi iṣẹ́", exampleTranslation: "My dad went to work", synonyms: "Bàbá", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọmọdé", definition: "Ọmọ kékeré", translation: "Child/Young person", partOfSpeech: "noun", pronunciation: "OH-moh-deh", exampleSentence: "Ọmọdé yìí jẹ́ ọmọ ònà", exampleTranslation: "This child is well-behaved", synonyms: "Ọmọ", antonyms: "Àgbàlagbà", difficulty: "EASY", languageCode: "yo" },
      { word: "Ìdílé", definition: "Àwọn ènìyàn tí ó jọra ní ẹbí", translation: "Family", partOfSpeech: "noun", pronunciation: "ee-DEE-leh", exampleSentence: "Ìdílé mi tóbi", exampleTranslation: "My family is big", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
    ]
  },
  {
    title: "Ara Ẹnìyàn",
    description: "Àwọn ọ̀rọ̀ tí ó jẹ́ mọ́ àwọn ẹ̀yà ara",
    translation: "Body Parts",
    level: "A1",
    difficulty: "BEGINNER",
    order: 4,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Orí", definition: "Apá tó wà ní òkè ara", translation: "Head", partOfSpeech: "noun", pronunciation: "OH-ree", exampleSentence: "Orí mi dùn", exampleTranslation: "My head hurts", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ojú", definition: "Apá ara tí a fi ń rí nǹkan", translation: "Eye", partOfSpeech: "noun", pronunciation: "OH-joo", exampleSentence: "Ojú mi wà lára", exampleTranslation: "My eyes are beautiful", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Etí", definition: "Apá ara tí a fi ń gbọ́ ohun", translation: "Ear", partOfSpeech: "noun", pronunciation: "EH-tee", exampleSentence: "Etí mi dùn", exampleTranslation: "My ear hurts", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Imú", definition: "Apá ara tí a fi ń mímí", translation: "Nose", partOfSpeech: "noun", pronunciation: "EE-moo", exampleSentence: "Imú mi tóbi", exampleTranslation: "My nose is big", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ẹnu", definition: "Apá ara tí a fi ń jẹun àti sọ̀rọ̀", translation: "Mouth", partOfSpeech: "noun", pronunciation: "EH-noo", exampleSentence: "Ẹnu mi ń dùn", exampleTranslation: "My mouth hurts", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọwọ́", definition: "Apá ara tí a fi ń ṣe nǹkan", translation: "Hand", partOfSpeech: "noun", pronunciation: "OH-woh", exampleSentence: "Ọwọ́ mi tóbi", exampleTranslation: "My hand is big", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ẹsẹ̀", definition: "Apá ara tí a fi ń rìn", translation: "Leg/Foot", partOfSpeech: "noun", pronunciation: "EH-seh", exampleSentence: "Ẹsẹ̀ mi dùn", exampleTranslation: "My leg hurts", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Inú", definition: "Apá inú ara", translation: "Stomach", partOfSpeech: "noun", pronunciation: "EE-noo", exampleSentence: "Inú mi ń dùn", exampleTranslation: "My stomach hurts", synonyms: "Ikun", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ikun", definition: "Apá ara tí a fi ń tọ́jú oúnjẹ", translation: "Belly", partOfSpeech: "noun", pronunciation: "EE-koon", exampleSentence: "Ikun mi tóbi", exampleTranslation: "My belly is big", synonyms: "Inú", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Orílẹ̀", definition: "Apá tó wà lórí", translation: "Hair/Head", partOfSpeech: "noun", pronunciation: "OH-ree-leh", exampleSentence: "Orílẹ̀ mi dàrà", exampleTranslation: "My hair is nice", synonyms: "", antonyms: "", difficulty: "MEDIUM", languageCode: "yo" },
      { word: "Ẹ̀yìn", definition: "Apá tó wà lẹ́yìn", translation: "Back", partOfSpeech: "noun", pronunciation: "EH-yin", exampleSentence: "Ẹ̀yìn mi dùn", exampleTranslation: "My back hurts", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ọkàn", definition: "Apá tó ń lù ní ara", translation: "Heart", partOfSpeech: "noun", pronunciation: "OH-kan", exampleSentence: "Ọkàn mi ń lù", exampleTranslation: "My heart is beating", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Ẹ̀jẹ̀", definition: "Omi pupa tó ń sàn ní ara", translation: "Blood", partOfSpeech: "noun", pronunciation: "EH-jeh", exampleSentence: "Ẹ̀jẹ̀ mi wà ní gbogbo ara", exampleTranslation: "My blood runs through my whole body", synonyms: "", antonyms: "", difficulty: "MEDIUM", languageCode: "yo" },
    ]
  },
  {
    title: "Àwọn Kọ́lọ́kọ́ (Awọ̀)",
    description: "Àwọn ọ̀rọ̀ tí ó jẹ́ mọ́ àwọn awọ̀",
    translation: "Colors",
    level: "A1",
    difficulty: "BEGINNER",
    order: 5,
    xpReward: 10,
    gemReward: 2,
    words: [
      { word: "Funfun", definition: "Awọ̀ tí ó dàbí ìwé tàbí yinyin", translation: "White", partOfSpeech: "adjective", pronunciation: "FOON-foo", exampleSentence: "Aṣọ funfun yìí dára", exampleTranslation: "This white cloth is nice", synonyms: "", antonyms: "Dúdú", difficulty: "EASY", languageCode: "yo" },
      { word: "Dúdú", definition: "Awọ̀ tí ó dàbí alẹ́ tàbí èéfín", translation: "Black", partOfSpeech: "adjective", pronunciation: "DOO-doo", exampleSentence: "Ọkùnrin dúdú naa wà níbẹ̀", exampleTranslation: "The black man is there", synonyms: "", antonyms: "Funfun", difficulty: "EASY", languageCode: "yo" },
      { word: "Pupa", definition: "Awọ̀ tí ó dàbí ẹ̀jẹ̀ tàbí tomati", translation: "Red", partOfSpeech: "adjective", pronunciation: "POO-pa", exampleSentence: "Aṣọ pupa yìí dára", exampleTranslation: "This red cloth is nice", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Awòn", definition: "Awọ̀ tí ó dàbí òòrùn tàbí ọsàn", translation: "Yellow", partOfSpeech: "adjective", pronunciation: "ah-WOHN", exampleSentence: "Awọ̀n yìí dára", exampleTranslation: "This yellow is nice", synonyms: "Pọ́n", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Aláwọ̀ ewé", definition: "Awọ̀ tí ó dàbí ewé igi", translation: "Green", partOfSpeech: "adjective", pronunciation: "ah-LA-woh EH-weh", exampleSentence: "Igi aláwọ̀ ewé wà níbẹ̀", exampleTranslation: "The green tree is there", synonyms: "Ewé", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Buluu", definition: "Awọ̀ tí ó dàbí ọ̀run", translation: "Blue", partOfSpeech: "adjective", pronunciation: "BOO-loo", exampleSentence: "Aṣọ buluu yìí dára", exampleTranslation: "This blue cloth is nice", synonyms: "", antonyms: "", difficulty: "EASY", languageCode: "yo" },
      { word: "Brown", definition: "Awọ̀ tí ó dàbí ilẹ̀ tàbí igi", translation: "Brown", partOfSpeech: "adjective", pronunciation: "BROWN", exampleSentence: "Aṣọ brown yìí dára", exampleTranslation: "This brown cloth is nice", synonyms: "", antonyms: "", difficulty: "MEDIUM", languageCode: "yo" },
      { word: "Pink", definition: "Awọ̀ tí ó dàbí ẹran tàbí òdòdó", translation: "Pink", partOfSpeech: "adjective", pronunciation: "PINK", exampleSentence: "Aṣọ pink yìí dára", exampleTranslation: "This pink cloth is nice", synonyms: "", antonyms: "", difficulty: "MEDIUM", languageCode: "yo" },
      { word: "Gray", definition: "Awọ̀ tí ó dàbí eérú", translation: "Gray", partOfSpeech: "adjective", pronunciation: "GRAY", exampleSentence: "Aṣọ gray yìí dára", exampleTranslation: "This gray cloth is nice", synonyms: "Eérú", antonyms: "", difficulty: "MEDIUM", languageCode: "yo" },
    ]
  },
];
